export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Rectangle {
        background: transparent;
        border-color: #ff0000;
        border-width: 5px;
        height: 150px;
        width: 150px;
        x: 25px;
        y: 25px;
        Image {
            height: 140px;
            image-fit: contain;
            source: @image-url("images/stroke_inside.png");
            width: 140px;
            x: 5px;
            y: 5px;
        }
    }
}
