/* Generated by Qt PSD Exporter - LVGL C exporter */
#include "main_screen.h"

const int32_t main_screen_width = 320;
const int32_t main_screen_height = 240;

lv_obj_t * main_screen_create(lv_obj_t * parent)
{
    lv_obj_t * root = lv_obj_create(parent);
    lv_obj_set_pos(root, 0, 0);
    lv_obj_set_size(root, 320, 240);
    lv_obj_set_style_pad_all(root, 0, 0);
    lv_obj_set_style_border_width(root, 0, 0);
    lv_obj_set_style_radius(root, 0, 0);
    lv_obj_set_style_bg_opa(root, 0, 0);
    lv_obj_set_scrollbar_mode(root, LV_SCROLLBAR_MODE_OFF);
    {
        lv_obj_t * obj_0 = lv_obj_create(root);
        lv_obj_set_pos(obj_0, 0, 0);
        lv_obj_set_size(obj_0, 320, 240);
        lv_obj_set_style_bg_color(obj_0, lv_color_hex(0x012401), 0);
        lv_obj_set_style_bg_opa(obj_0, 255, 0);
    }
    {
        lv_obj_t * obj_1 = lv_label_create(root);
        lv_obj_set_pos(obj_1, 0, 0);
        lv_obj_set_size(obj_1, 0, 0);
        lv_obj_set_style_text_align(obj_1, LV_TEXT_ALIGN_CENTER, 0);
        lv_obj_set_style_text_color(obj_1, lv_color_hex(0xeac3c3), 0);
        lv_obj_set_style_text_font(obj_1, &lv_font_montserrat_48, 0);
        lv_label_set_text(obj_1, "");
    }
    {
        lv_obj_t * obj_2 = lv_label_create(root);
        lv_obj_set_pos(obj_2, 2, 1);
        lv_obj_set_size(obj_2, 160, 88);
        lv_obj_set_style_text_align(obj_2, LV_TEXT_ALIGN_CENTER, 0);
        lv_obj_set_style_text_color(obj_2, lv_color_hex(0xeac3c3), 0);
        lv_obj_set_style_text_font(obj_2, &lv_font_montserrat_30, 0);
        lv_label_set_text(obj_2, "文字列中に\n改行");
    }
    {
        lv_obj_t * obj_3 = lv_label_create(root);
        lv_obj_set_pos(obj_3, 169, 1);
        lv_obj_set_size(obj_3, 144, 88);
        lv_obj_set_style_text_align(obj_3, LV_TEXT_ALIGN_CENTER, 0);
        lv_obj_set_style_text_color(obj_3, lv_color_hex(0xeac3c3), 0);
        lv_obj_set_style_text_font(obj_3, &lv_font_montserrat_30, 0);
        lv_label_set_text(obj_3, "文字列中に\n別フォント");
    }
    {
        lv_obj_t * obj_4 = lv_label_create(root);
        lv_obj_set_pos(obj_4, 25, 101);
        lv_obj_set_size(obj_4, 86, 88);
        lv_obj_set_style_text_align(obj_4, LV_TEXT_ALIGN_CENTER, 0);
        lv_obj_set_style_text_color(obj_4, lv_color_hex(0xeac3c3), 0);
        lv_obj_set_style_text_font(obj_4, &lv_font_montserrat_30, 0);
        lv_label_set_text(obj_4, "Shift\n+改行");
    }
    {
        lv_obj_t * obj_5 = lv_label_create(root);
        lv_obj_set_pos(obj_5, 160, 110);
        lv_obj_set_size(obj_5, 158, 116);
        lv_obj_set_style_text_align(obj_5, LV_TEXT_ALIGN_CENTER, 0);
        lv_obj_set_style_text_color(obj_5, lv_color_hex(0xeac3c3), 0);
        lv_obj_set_style_text_font(obj_5, &lv_font_montserrat_24, 0);
        lv_label_set_text(obj_5, "段落テキストは折り返される");
    }
    return root;
}
