export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Rectangle {
        height: 36px;
        width: 203px;
        x: 30px;
        y: 72px;
        VerticalLayout {
            padding: 0;
            HorizontalLayout {
                padding: 0;
                spacing: 0;
                Text {
                    color: #000000;
                    font-family: "Noto Color Emoji";
                    font-size: 36px;
                    horizontal-alignment: left;
                    text: "😀";
                }
                Text {
                    color: #000000;
                    font-family: "Noto Sans";
                    font-size: 36px;
                    horizontal-alignment: left;
                    text: "";
                }
                Text {
                    color: #000000;
                    font-family: "Noto Color Emoji";
                    font-size: 36px;
                    horizontal-alignment: left;
                    text: "🚀";
                }
                Text {
                    color: #000000;
                    font-family: "Noto Sans";
                    font-size: 36px;
                    horizontal-alignment: left;
                    text: "";
                }
                Text {
                    color: #000000;
                    font-family: "Noto Color Emoji";
                    font-size: 36px;
                    horizontal-alignment: left;
                    text: "❤";
                }
                Text {
                    color: #000000;
                    font-family: "Noto Sans";
                    font-size: 36px;
                    horizontal-alignment: left;
                    text: "";
                }
                Text {
                    color: #000000;
                    font-family: "Noto Color Emoji";
                    font-size: 36px;
                    horizontal-alignment: left;
                    text: "🌟";
                }
            }
        }
    }
}
