export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/bottom_red.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/middle_green.png");
        width: 200px;
        x: 20px;
        y: 20px;
    }
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/top_blue.png");
        width: 200px;
        x: 40px;
        y: 40px;
    }
}
