export component MainWindow inherits Window {
    height: 600px;
    title: "";
    width: 600px;
    x: 0px;
    y: 0px;
    Image {
        height: 600px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 600px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        height: 37px;
        text: "";
        width: 169px;
        x: 52px;
        y: 64px;
    }
}
