export component MainWindow inherits Window {
    height: 300px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 300px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Roboto";
        font-size: 24px;
        height: 32px;
        horizontal-alignment: left;
        text: "Line A\nLine B\nLine C";
        width: 66px;
        x: 30px;
        y: 35px;
    }
}
