export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Roboto";
        font-size: 14px;
        height: 161px;
        horizontal-alignment: left;
        overflow: clip;
        text: "Internationalization implementation characterization extraordinarily";
        vertical-alignment: bottom;
        width: 160px;
        wrap: word-wrap;
        x: 20px;
        y: 19px;
    }
}
