/* Generated by Qt PSD Exporter - LVGL C exporter */
#include "main_screen.h"

const int32_t main_screen_width = 4000;
const int32_t main_screen_height = 4000;

lv_obj_t * main_screen_create(lv_obj_t * parent)
{
    lv_obj_t * root = lv_obj_create(parent);
    lv_obj_set_pos(root, 0, 0);
    lv_obj_set_size(root, 4000, 4000);
    lv_obj_set_style_pad_all(root, 0, 0);
    lv_obj_set_style_border_width(root, 0, 0);
    lv_obj_set_style_radius(root, 0, 0);
    lv_obj_set_style_bg_opa(root, 0, 0);
    lv_obj_set_scrollbar_mode(root, LV_SCROLLBAR_MODE_OFF);
    {
        lv_obj_t * obj_0 = lv_image_create(root);
        lv_obj_set_pos(obj_0, 0, 0);
        lv_obj_set_size(obj_0, 4000, 4000);
        lv_image_set_src(obj_0, "A:images/background.png");
    }
    {
        lv_obj_t * obj_1 = lv_label_create(root);
        lv_obj_set_pos(obj_1, 1800, 1916);
        lv_obj_set_size(obj_1, 435, 105);
        lv_obj_set_style_text_align(obj_1, LV_TEXT_ALIGN_LEFT, 0);
        lv_obj_set_style_text_color(obj_1, lv_color_hex(0x000000), 0);
        lv_obj_set_style_text_font(obj_1, &lv_font_montserrat_48, 0);
        lv_label_set_text(obj_1, "Large Canvas");
    }
    return root;
}
