export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Text {
        clip: true;
        color: #000000;
        font-family: "Roboto";
        font-italic: true;
        font-size: 30px;
        height: 39px;
        horizontal-alignment: left;
        text: "Faux Italic";
        vertical-alignment: bottom;
        width: 137px;
        x: 20px;
        y: 69px;
    }
}
