/* Generated by Qt PSD Exporter - LVGL C exporter */
#include "main_screen.h"

const int32_t main_screen_width = 200;
const int32_t main_screen_height = 200;

lv_obj_t * main_screen_create(lv_obj_t * parent)
{
    static lv_grad_dsc_t grad_gradient_shape_0;
    {
        static const lv_color_t stops_gradient_shape_0_colors[] = { LV_COLOR_MAKE(0xff, 0x0, 0x0), LV_COLOR_MAKE(0x0, 0x0, 0xff), };
        static const lv_opa_t stops_gradient_shape_0_opa[] = { 255, 255, };
        static const uint8_t stops_gradient_shape_0_fracs[] = { 0, 255, };
        lv_grad_linear_init(&grad_gradient_shape_0, 21, 121, 121, 21, LV_GRAD_EXTEND_PAD);
        lv_grad_init_stops(&grad_gradient_shape_0, stops_gradient_shape_0_colors, stops_gradient_shape_0_opa, stops_gradient_shape_0_fracs, 2);
    }

    lv_obj_t * root = lv_obj_create(parent);
    lv_obj_set_pos(root, 0, 0);
    lv_obj_set_size(root, 200, 200);
    lv_obj_set_style_pad_all(root, 0, 0);
    lv_obj_set_style_border_width(root, 0, 0);
    lv_obj_set_style_radius(root, 0, 0);
    lv_obj_set_style_bg_opa(root, 0, 0);
    lv_obj_set_scrollbar_mode(root, LV_SCROLLBAR_MODE_OFF);
    {
        lv_obj_t * obj_0 = lv_image_create(root);
        lv_obj_set_pos(obj_0, 0, 0);
        lv_obj_set_size(obj_0, 200, 200);
        lv_image_set_src(obj_0, "A:images/background.png");
    }
    {
        lv_obj_t * obj_1 = lv_obj_create(root);
        lv_obj_set_pos(obj_1, 29, 29);
        lv_obj_set_size(obj_1, 142, 142);
        lv_obj_set_style_bg_grad(obj_1, &grad_gradient_shape_0, 0);
        lv_obj_set_style_bg_opa(obj_1, 255, 0);
        lv_obj_set_style_border_width(obj_1, 0, 0);
    }
    return root;
}
