export component MainWindow inherits Window {
    height: 500px;
    title: "";
    width: 500px;
    x: 0px;
    y: 0px;
    Image {
        height: 500px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 500px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l1.png");
        width: 50px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l2.png");
        width: 50px;
        x: 50px;
        y: 0px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l3.png");
        width: 50px;
        x: 100px;
        y: 0px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l4.png");
        width: 50px;
        x: 150px;
        y: 0px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l5.png");
        width: 50px;
        x: 200px;
        y: 0px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l6.png");
        width: 50px;
        x: 250px;
        y: 0px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l7.png");
        width: 50px;
        x: 300px;
        y: 0px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l8.png");
        width: 50px;
        x: 350px;
        y: 0px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l9.png");
        width: 50px;
        x: 400px;
        y: 0px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l10.png");
        width: 50px;
        x: 450px;
        y: 0px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l11.png");
        width: 50px;
        x: 0px;
        y: 50px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l12.png");
        width: 50px;
        x: 50px;
        y: 50px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l13.png");
        width: 50px;
        x: 100px;
        y: 50px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l14.png");
        width: 50px;
        x: 150px;
        y: 50px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l15.png");
        width: 50px;
        x: 200px;
        y: 50px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l16.png");
        width: 50px;
        x: 250px;
        y: 50px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l17.png");
        width: 50px;
        x: 300px;
        y: 50px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l18.png");
        width: 50px;
        x: 350px;
        y: 50px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l19.png");
        width: 50px;
        x: 400px;
        y: 50px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l20.png");
        width: 50px;
        x: 450px;
        y: 50px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l21.png");
        width: 50px;
        x: 0px;
        y: 100px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l22.png");
        width: 50px;
        x: 50px;
        y: 100px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l23.png");
        width: 50px;
        x: 100px;
        y: 100px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l24.png");
        width: 50px;
        x: 150px;
        y: 100px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l25.png");
        width: 50px;
        x: 200px;
        y: 100px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l26.png");
        width: 50px;
        x: 250px;
        y: 100px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l27.png");
        width: 50px;
        x: 300px;
        y: 100px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l28.png");
        width: 50px;
        x: 350px;
        y: 100px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l29.png");
        width: 50px;
        x: 400px;
        y: 100px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l30.png");
        width: 50px;
        x: 450px;
        y: 100px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l31.png");
        width: 50px;
        x: 0px;
        y: 150px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l32.png");
        width: 50px;
        x: 50px;
        y: 150px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l33.png");
        width: 50px;
        x: 100px;
        y: 150px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l34.png");
        width: 50px;
        x: 150px;
        y: 150px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l35.png");
        width: 50px;
        x: 200px;
        y: 150px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l36.png");
        width: 50px;
        x: 250px;
        y: 150px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l37.png");
        width: 50px;
        x: 300px;
        y: 150px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l38.png");
        width: 50px;
        x: 350px;
        y: 150px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l39.png");
        width: 50px;
        x: 400px;
        y: 150px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l40.png");
        width: 50px;
        x: 450px;
        y: 150px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l41.png");
        width: 50px;
        x: 0px;
        y: 200px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l42.png");
        width: 50px;
        x: 50px;
        y: 200px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l43.png");
        width: 50px;
        x: 100px;
        y: 200px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l44.png");
        width: 50px;
        x: 150px;
        y: 200px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l45.png");
        width: 50px;
        x: 200px;
        y: 200px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l46.png");
        width: 50px;
        x: 250px;
        y: 200px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l47.png");
        width: 50px;
        x: 300px;
        y: 200px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l48.png");
        width: 50px;
        x: 350px;
        y: 200px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l49.png");
        width: 50px;
        x: 400px;
        y: 200px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l50.png");
        width: 50px;
        x: 450px;
        y: 200px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l51.png");
        width: 50px;
        x: 0px;
        y: 250px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l52.png");
        width: 50px;
        x: 50px;
        y: 250px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l53.png");
        width: 50px;
        x: 100px;
        y: 250px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l54.png");
        width: 50px;
        x: 150px;
        y: 250px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l55.png");
        width: 50px;
        x: 200px;
        y: 250px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l56.png");
        width: 50px;
        x: 250px;
        y: 250px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l57.png");
        width: 50px;
        x: 300px;
        y: 250px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l58.png");
        width: 50px;
        x: 350px;
        y: 250px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l59.png");
        width: 50px;
        x: 400px;
        y: 250px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l60.png");
        width: 50px;
        x: 450px;
        y: 250px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l61.png");
        width: 50px;
        x: 0px;
        y: 300px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l62.png");
        width: 50px;
        x: 50px;
        y: 300px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l63.png");
        width: 50px;
        x: 100px;
        y: 300px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l64.png");
        width: 50px;
        x: 150px;
        y: 300px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l65.png");
        width: 50px;
        x: 200px;
        y: 300px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l66.png");
        width: 50px;
        x: 250px;
        y: 300px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l67.png");
        width: 50px;
        x: 300px;
        y: 300px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l68.png");
        width: 50px;
        x: 350px;
        y: 300px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l69.png");
        width: 50px;
        x: 400px;
        y: 300px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l70.png");
        width: 50px;
        x: 450px;
        y: 300px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l71.png");
        width: 50px;
        x: 0px;
        y: 350px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l72.png");
        width: 50px;
        x: 50px;
        y: 350px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l73.png");
        width: 50px;
        x: 100px;
        y: 350px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l74.png");
        width: 50px;
        x: 150px;
        y: 350px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l75.png");
        width: 50px;
        x: 200px;
        y: 350px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l76.png");
        width: 50px;
        x: 250px;
        y: 350px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l77.png");
        width: 50px;
        x: 300px;
        y: 350px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l78.png");
        width: 50px;
        x: 350px;
        y: 350px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l79.png");
        width: 50px;
        x: 400px;
        y: 350px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l80.png");
        width: 50px;
        x: 450px;
        y: 350px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l81.png");
        width: 50px;
        x: 0px;
        y: 400px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l82.png");
        width: 50px;
        x: 50px;
        y: 400px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l83.png");
        width: 50px;
        x: 100px;
        y: 400px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l84.png");
        width: 50px;
        x: 150px;
        y: 400px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l85.png");
        width: 50px;
        x: 200px;
        y: 400px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l86.png");
        width: 50px;
        x: 250px;
        y: 400px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l87.png");
        width: 50px;
        x: 300px;
        y: 400px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l88.png");
        width: 50px;
        x: 350px;
        y: 400px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l89.png");
        width: 50px;
        x: 400px;
        y: 400px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l90.png");
        width: 50px;
        x: 450px;
        y: 400px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l91.png");
        width: 50px;
        x: 0px;
        y: 450px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l92.png");
        width: 50px;
        x: 50px;
        y: 450px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l93.png");
        width: 50px;
        x: 100px;
        y: 450px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l94.png");
        width: 50px;
        x: 150px;
        y: 450px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l95.png");
        width: 50px;
        x: 200px;
        y: 450px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l96.png");
        width: 50px;
        x: 250px;
        y: 450px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l97.png");
        width: 50px;
        x: 300px;
        y: 450px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l98.png");
        width: 50px;
        x: 350px;
        y: 450px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l99.png");
        width: 50px;
        x: 400px;
        y: 450px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/l100.png");
        width: 50px;
        x: 450px;
        y: 450px;
    }
}
