export component MainWindow inherits Window {
    height: 300px;
    title: "";
    width: 400px;
    x: 0px;
    y: 0px;
    Image {
        height: 300px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 400px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Roboto";
        font-size: 14px;
        height: 261px;
        horizontal-alignment: left;
        text: "First paragraph with indent. This is a longer text to test paragraph formatting.\n\nSecond paragraph.";
        width: 360px;
        x: 20px;
        y: 19px;
    }
}
