export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Rectangle {
        height: 162px;
        width: 262px;
        x: 19px;
        y: 19px;
        Rectangle {
            background: #0064c8;
            height: 160px;
            width: 260px;
            x: 1px;
            y: 1px;
        }
    }
    Text {
        color: #ffffff;
        font-family: "Roboto";
        font-size: 24px;
        height: 32px;
        horizontal-alignment: center;
        text: "CLICK ME";
        width: 107px;
        x: 21px;
        y: 90px;
    }
}
