export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Rectangle {
        background: transparent;
        border-color: #ff0000;
        border-width: 3px;
        height: 100px;
        width: 200px;
        x: 50px;
        y: 50px;
        Image {
            height: 100px;
            image-fit: contain;
            source: @image-url("images/stroke_layer.png");
            width: 200px;
        }
    }
}
