/* Generated by Qt PSD Exporter - LVGL C exporter */
#include "main_screen.h"

const int32_t main_screen_width = 320;
const int32_t main_screen_height = 240;

lv_obj_t * main_screen_create(lv_obj_t * parent)
{
    lv_obj_t * root = lv_obj_create(parent);
    lv_obj_set_pos(root, 0, 0);
    lv_obj_set_size(root, 320, 240);
    lv_obj_set_style_pad_all(root, 0, 0);
    lv_obj_set_style_border_width(root, 0, 0);
    lv_obj_set_style_radius(root, 0, 0);
    lv_obj_set_style_bg_opa(root, 0, 0);
    lv_obj_set_scrollbar_mode(root, LV_SCROLLBAR_MODE_OFF);
    {
        lv_obj_t * obj_0 = lv_obj_create(root);
        lv_obj_set_pos(obj_0, 0, 0);
        lv_obj_set_size(obj_0, 320, 240);
        lv_obj_set_style_bg_color(obj_0, lv_color_hex(0x8fc5f3), 0);
        lv_obj_set_style_bg_opa(obj_0, 255, 0);
    }
    {
        lv_obj_t * obj_1 = lv_image_create(root);
        lv_obj_set_pos(obj_1, 54, 65);
        lv_obj_set_size(obj_1, 153, 114);
        lv_image_set_src(obj_1, "A:images/0f4b3809aab3e047.png");
        lv_obj_set_style_opa(obj_1, 94, 0);
    }
    {
        lv_obj_t * obj_2 = lv_image_create(root);
        lv_obj_set_pos(obj_2, 170, 75);
        lv_obj_set_size(obj_2, 133, 95);
        lv_image_set_src(obj_2, "A:images/0f4b3809aab3e047_1.png");
        lv_obj_set_style_opa(obj_2, 94, 0);
    }
    return root;
}
