export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        image-fit: contain;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        height: 140px;
        image-fit: contain;
        source: @image-url("images/base.png");
        width: 140px;
        x: 30px;
        y: 30px;
    }
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/clip_1.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 100px;
        image-fit: contain;
        opacity: 0.501961;
        source: @image-url("images/clip_2.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
}
