export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 47px;
        image-fit: contain;
        source: @image-url("images/shelllower.png");
        width: 260px;
        x: 35px;
        y: 93px;
    }
}
