/* Generated by Qt PSD Exporter - LVGL C exporter */
#include "main_screen.h"

const int32_t main_screen_width = 320;
const int32_t main_screen_height = 240;

lv_obj_t * main_screen_create(lv_obj_t * parent)
{
    lv_obj_t * root = lv_obj_create(parent);
    lv_obj_set_pos(root, 0, 0);
    lv_obj_set_size(root, 320, 240);
    lv_obj_set_style_pad_all(root, 0, 0);
    lv_obj_set_style_border_width(root, 0, 0);
    lv_obj_set_style_radius(root, 0, 0);
    lv_obj_set_style_bg_opa(root, 0, 0);
    lv_obj_set_scrollbar_mode(root, LV_SCROLLBAR_MODE_OFF);
    {
        lv_obj_t * obj_0 = lv_obj_create(root);
        lv_obj_set_pos(obj_0, 0, 0);
        lv_obj_set_size(obj_0, 320, 240);
        lv_obj_set_style_bg_color(obj_0, lv_color_hex(0x5d5206), 0);
        lv_obj_set_style_bg_opa(obj_0, 255, 0);
    }
    {
        lv_obj_t * obj_1 = lv_obj_create(root);
        lv_obj_set_pos(obj_1, 48, 79);
        lv_obj_set_size(obj_1, 163, 62);
        lv_obj_set_style_bg_color(obj_1, lv_color_hex(0xf5f5ed), 0);
        lv_obj_set_style_bg_opa(obj_1, 255, 0);
        lv_obj_set_style_border_width(obj_1, 0, 0);
    }
    {
        lv_obj_t * obj_2 = lv_obj_create(root);
        lv_obj_set_pos(obj_2, 52, 80);
        lv_obj_set_size(obj_2, 157, 34);
        lv_obj_set_style_bg_color(obj_2, lv_color_hex(0xf7e790), 0);
        lv_obj_set_style_bg_opa(obj_2, 255, 0);
        lv_obj_set_style_border_width(obj_2, 0, 0);
    }
    {
        lv_obj_t * obj_3 = lv_label_create(root);
        lv_obj_set_pos(obj_3, 50, 71);
        lv_obj_set_size(obj_3, 160, 44);
        lv_obj_set_style_text_align(obj_3, LV_TEXT_ALIGN_CENTER, 0);
        lv_obj_set_style_text_color(obj_3, lv_color_hex(0x000000), 0);
        lv_obj_set_style_text_font(obj_3, &lv_font_montserrat_30, 0);
        lv_label_set_text(obj_3, "Example1");
    }
    return root;
}
