export component MainWindow inherits Window {
    height: 300px;
    title: "";
    width: 400px;
    x: 0px;
    y: 0px;
    Image {
        height: 300px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 400px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Roboto";
        font-size: 36px;
        height: 48px;
        horizontal-alignment: left;
        text: "Wave Text";
        width: 164px;
        x: 80px;
        y: 112px;
    }
}
