export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Rectangle {
        height: 200px;
        width: 200px;
        x: 0px;
        y: 0px;
        Rectangle {
            background: @radial-gradient(circle, #ff0000 0%, #0000ff 70.7107%, #0000ff 100%);
            height: 200px;
            width: 200px;
            x: 0px;
            y: 0px;
        }
    }
}
