export component MainWindow inherits Window {
    height: 300px;
    title: "";
    width: 400px;
    x: 0px;
    y: 0px;
    Image {
        height: 300px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 400px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Roboto";
        font-size: 16px;
        height: 252px;
        horizontal-alignment: left;
        text: "Paragraph text in a bounding box. This text wraps automatically when it reaches the edge of the box.";
        width: 354px;
        x: 25px;
        y: 23px;
    }
}
