export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/d953ee13be5cbb46.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/471b942182a4e41b.png");
        width: 200px;
        x: 0px;
        y: 50px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/4b3d9f4f6e50544b.png");
        width: 200px;
        x: 0px;
        y: 100px;
    }
    Image {
        height: 50px;
        image-fit: contain;
        source: @image-url("images/668aa0e7340f06f7.png");
        width: 200px;
        x: 0px;
        y: 150px;
    }
}
