export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 120px;
        image-fit: contain;
        opacity: 0.501961;
        source: @image-url("images/knockout_shadow.png");
        width: 120px;
        x: 40px;
        y: 40px;
    }
}
