export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Roboto";
        font-size: 14px;
        height: 181px;
        horizontal-alignment: left;
        text: "This text is fully justified including the last line of each paragraph.";
        width: 283px;
        x: 10px;
        y: 9px;
    }
}
