export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Rectangle {
        height: 146px;
        width: 146px;
        x: 27px;
        y: 27px;
        Rectangle {
            height: 140px;
            width: 140px;
            x: 3px;
            y: 3px;
        }
    }
}
