export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Rectangle {
        height: 146px;
        width: 146px;
        x: 27px;
        y: 27px;
        Rectangle {
            border-color: #ff0000;
            border-width: 3px;
            height: 143px;
            width: 143px;
            x: 1px;
            y: 1px;
        }
    }
}
