export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/layer_1.png");
        width: 60px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/layer_2.png");
        width: 60px;
        x: 60px;
        y: 0px;
    }
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/layer_3.png");
        width: 60px;
        x: 120px;
        y: 0px;
    }
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/layer_4.png");
        width: 60px;
        x: 180px;
        y: 0px;
    }
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/layer_5.png");
        width: 60px;
        x: 240px;
        y: 0px;
    }
}
