export component MainWindow inherits Window {
    height: 4000px;
    title: "";
    width: 4000px;
    x: 0px;
    y: 0px;
    Image {
        height: 4000px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 4000px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Roboto";
        font-size: 72px;
        height: 95px;
        horizontal-alignment: left;
        text: "Large Canvas";
        width: 435px;
        x: 1800px;
        y: 1925px;
    }
}
