export component MainWindow inherits Window {
    height: 4000px;
    title: "";
    width: 4000px;
    x: 0px;
    y: 0px;
    Image {
        height: 4000px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 4000px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Sans Serif";
        font-size: 9px;
        height: 67px;
        horizontal-alignment: left;
        text: "";
        width: 425px;
        x: 1806px;
        y: 1948px;
    }
}
