export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 400px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 400px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Roboto";
        font-size: 72px;
        height: 95px;
        horizontal-alignment: left;
        text: "Big";
        width: 103px;
        x: 50px;
        y: 75px;
    }
}
