export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 400px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 400px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        height: 67px;
        text: "";
        width: 92px;
        x: 56px;
        y: 98px;
    }
}
