export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 76px;
        image-fit: contain;
        source: @image-url("images/motion_blurred.png");
        width: 74px;
        x: 63px;
        y: 62px;
    }
}
