export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Rectangle {
        height: 148px;
        width: 148px;
        x: 26px;
        y: 26px;
        Rectangle {
            background: #e6e6e6;
            border-color: #000000;
            border-width: 5px;
            height: 145px;
            width: 145px;
            x: 1px;
            y: 1px;
        }
    }
}
