export component MainWindow inherits Window {
    height: 300px;
    title: "";
    width: 400px;
    x: 0px;
    y: 0px;
    Image {
        height: 300px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 400px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 100px;
        image-fit: contain;
        source: @image-url("images/raster_circle.png");
        width: 100px;
        x: 50px;
        y: 50px;
    }
    Text {
        color: #000000;
        font-family: "Roboto";
        font-size: 28px;
        height: 37px;
        horizontal-alignment: left;
        text: "Mixed Content";
        width: 183px;
        x: 50px;
        y: 221px;
    }
    Rectangle {
        height: 152px;
        width: 172px;
        x: 199px;
        y: 49px;
        Rectangle {
            background: #0064c8;
            height: 150px;
            width: 170px;
            x: 1px;
            y: 1px;
        }
    }
}
