export component MainWindow inherits Window {
    height: 100px;
    title: "";
    width: 640px;
    x: 0px;
    y: 0px;
    Rectangle {
        color: #bcf5bc;
        height: 100px;
        width: 640px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "SourceHanSans-Medium";
        font-size: 50px;
        height: 70px;
        horizontal-alignment: center;
        text: "hug";
        vertical-alignment: center;
        width: 99px;
        x: 20px;
        y: 20px;
    }
    Text {
        color: #000000;
        font-family: "TimesNewRomanPSMT";
        font-size: 50px;
        height: 58px;
        horizontal-alignment: center;
        text: "hug";
        vertical-alignment: center;
        width: 87px;
        x: 120px;
        y: 20px;
    }
    Text {
        color: #000000;
        font-family: "Wingdings";
        font-size: 50px;
        height: 54px;
        horizontal-alignment: center;
        text: "hub";
        vertical-alignment: center;
        width: 154px;
        x: 420px;
        y: 20px;
    }
    Text {
        color: #000000;
        font-family: "MS PMincho";
        font-size: 50px;
        height: 48px;
        horizontal-alignment: center;
        text: "hug";
        vertical-alignment: center;
        width: 82px;
        x: 210px;
        y: 21px;
    }
    Text {
        color: #000000;
        font-family: "Exo2Roman-Thin";
        font-size: 50px;
        height: 58px;
        horizontal-alignment: center;
        text: "hug";
        vertical-alignment: center;
        width: 91px;
        x: 310px;
        y: 20px;
    }
}
