export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Roboto";
        font-size: 36px;
        height: 48px;
        horizontal-alignment: left;
        text: "INFLATE";
        width: 140px;
        x: 50px;
        y: 82px;
    }
}
