export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Rectangle {
        height: 202px;
        width: 202px;
        x: -1px;
        y: -1px;
        Rectangle {
            background: #0080ff;
            height: 200px;
            width: 200px;
            x: 1px;
            y: 1px;
        }
    }
}
