export component MainWindow inherits Window {
    height: 400px;
    title: "";
    width: 600px;
    x: 0px;
    y: 0px;
    Image {
        height: 400px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 600px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        height: 180px;
        text: "";
        width: 553px;
        x: 19px;
        y: 20px;
    }
}
