export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Rectangle {
        height: 162px;
        width: 162px;
        x: 19px;
        y: 19px;
        Rectangle {
            background: #c83264;
            border-radius: 80px;
            height: 160px;
            width: 160px;
            x: 1px;
            y: 1px;
        }
    }
}
