export component MainWindow inherits Window {
    height: 300px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 300px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 206px;
        image-fit: contain;
        source: @image-url("images/transformed.png");
        width: 204px;
        x: 48px;
        y: 47px;
    }
}
