export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Roboto";
        font-size: 8px;
        height: 10px;
        horizontal-alignment: left;
        text: "Tiny text at 8pt";
        width: 53px;
        x: 10px;
        y: 42px;
    }
}
