export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        height: 8px;
        text: "";
        width: 53px;
        x: 10px;
        y: 44px;
    }
}
