/* Generated by Qt PSD Exporter - LVGL C exporter */
#include "main_screen.h"

const int32_t main_screen_width = 200;
const int32_t main_screen_height = 200;

lv_obj_t * main_screen_create(lv_obj_t * parent)
{
    lv_obj_t * root = lv_obj_create(parent);
    lv_obj_set_pos(root, 0, 0);
    lv_obj_set_size(root, 200, 200);
    lv_obj_set_style_pad_all(root, 0, 0);
    lv_obj_set_style_border_width(root, 0, 0);
    lv_obj_set_style_radius(root, 0, 0);
    lv_obj_set_style_bg_opa(root, 0, 0);
    lv_obj_set_scrollbar_mode(root, LV_SCROLLBAR_MODE_OFF);
    {
        lv_obj_t * obj_0 = lv_image_create(root);
        lv_obj_set_pos(obj_0, 0, 0);
        lv_obj_set_size(obj_0, 200, 200);
        lv_image_set_src(obj_0, "A:images/background.png");
    }
    {
        lv_obj_t * obj_1 = lv_image_create(root);
        lv_obj_set_pos(obj_1, 0, 0);
        lv_obj_set_size(obj_1, 0, 0);
        lv_image_set_src(obj_1, "A:images/");
        lv_obj_set_style_opa(obj_1, 184, 0);
    }
    {
        lv_obj_t * obj_2 = lv_image_create(root);
        lv_obj_set_pos(obj_2, 0, 0);
        lv_obj_set_size(obj_2, 0, 0);
        lv_image_set_src(obj_2, "A:images/");
        lv_obj_set_style_opa(obj_2, 204, 0);
    }
    {
        lv_obj_t * obj_3 = lv_image_create(root);
        lv_obj_set_pos(obj_3, 0, 0);
        lv_obj_set_size(obj_3, 0, 0);
        lv_image_set_src(obj_3, "A:images/");
        lv_obj_set_style_opa(obj_3, 125, 0);
    }
    {
        lv_obj_t * obj_4 = lv_image_create(root);
        lv_obj_set_pos(obj_4, 0, 0);
        lv_obj_set_size(obj_4, 0, 0);
        lv_image_set_src(obj_4, "A:images/");
        lv_obj_set_style_opa(obj_4, 26, 0);
    }
    {
        lv_obj_t * obj_5 = lv_image_create(root);
        lv_obj_set_pos(obj_5, 0, 0);
        lv_obj_set_size(obj_5, 0, 0);
        lv_image_set_src(obj_5, "A:images/");
        lv_obj_set_style_opa(obj_5, 150, 0);
    }
    {
        lv_obj_t * obj_6 = lv_image_create(root);
        lv_obj_set_pos(obj_6, 0, 0);
        lv_obj_set_size(obj_6, 0, 0);
        lv_image_set_src(obj_6, "A:images/");
        lv_obj_set_style_opa(obj_6, 33, 0);
    }
    {
        lv_obj_t * obj_7 = lv_image_create(root);
        lv_obj_set_pos(obj_7, 0, 0);
        lv_obj_set_size(obj_7, 0, 0);
        lv_image_set_src(obj_7, "A:images/");
        lv_obj_set_style_opa(obj_7, 107, 0);
    }
    {
        lv_obj_t * obj_8 = lv_image_create(root);
        lv_obj_set_pos(obj_8, 0, 0);
        lv_obj_set_size(obj_8, 0, 0);
        lv_image_set_src(obj_8, "A:images/");
        lv_obj_set_style_opa(obj_8, 189, 0);
    }
    {
        lv_obj_t * obj_9 = lv_image_create(root);
        lv_obj_set_pos(obj_9, 0, 0);
        lv_obj_set_size(obj_9, 0, 0);
        lv_image_set_src(obj_9, "A:images/");
        lv_obj_set_style_opa(obj_9, 71, 0);
    }
    {
        lv_obj_t * obj_10 = lv_image_create(root);
        lv_obj_set_pos(obj_10, 0, 0);
        lv_obj_set_size(obj_10, 0, 0);
        lv_image_set_src(obj_10, "A:images/");
        lv_obj_set_style_opa(obj_10, 51, 0);
    }
    {
        lv_obj_t * obj_11 = lv_image_create(root);
        lv_obj_set_pos(obj_11, 0, 0);
        lv_obj_set_size(obj_11, 0, 0);
        lv_image_set_src(obj_11, "A:images/");
        lv_obj_set_style_opa(obj_11, 105, 0);
    }
    {
        lv_obj_t * obj_12 = lv_image_create(root);
        lv_obj_set_pos(obj_12, 0, 0);
        lv_obj_set_size(obj_12, 0, 0);
        lv_image_set_src(obj_12, "A:images/");
        lv_obj_set_style_opa(obj_12, 217, 0);
    }
    {
        lv_obj_t * obj_13 = lv_image_create(root);
        lv_obj_set_pos(obj_13, 0, 0);
        lv_obj_set_size(obj_13, 0, 0);
        lv_image_set_src(obj_13, "A:images/");
        lv_obj_set_style_opa(obj_13, 59, 0);
    }
    {
        lv_obj_t * obj_14 = lv_image_create(root);
        lv_obj_set_pos(obj_14, 0, 0);
        lv_obj_set_size(obj_14, 0, 0);
        lv_image_set_src(obj_14, "A:images/");
        lv_obj_set_style_opa(obj_14, 135, 0);
    }
    {
        lv_obj_t * obj_15 = lv_image_create(root);
        lv_obj_set_pos(obj_15, 0, 0);
        lv_obj_set_size(obj_15, 0, 0);
        lv_image_set_src(obj_15, "A:images/");
        lv_obj_set_style_opa(obj_15, 161, 0);
    }
    {
        lv_obj_t * obj_16 = lv_image_create(root);
        lv_obj_set_pos(obj_16, 0, 0);
        lv_obj_set_size(obj_16, 0, 0);
        lv_image_set_src(obj_16, "A:images/");
        lv_obj_set_style_opa(obj_16, 196, 0);
    }
    {
        lv_obj_t * obj_17 = lv_image_create(root);
        lv_obj_set_pos(obj_17, 0, 0);
        lv_obj_set_size(obj_17, 0, 0);
        lv_image_set_src(obj_17, "A:images/");
        lv_obj_set_style_opa(obj_17, 94, 0);
    }
    {
        lv_obj_t * obj_18 = lv_image_create(root);
        lv_obj_set_pos(obj_18, 0, 0);
        lv_obj_set_size(obj_18, 0, 0);
        lv_image_set_src(obj_18, "A:images/");
        lv_obj_set_style_opa(obj_18, 135, 0);
    }
    {
        lv_obj_t * obj_19 = lv_image_create(root);
        lv_obj_set_pos(obj_19, 0, 0);
        lv_obj_set_size(obj_19, 0, 0);
        lv_image_set_src(obj_19, "A:images/");
        lv_obj_set_style_opa(obj_19, 38, 0);
    }
    {
        lv_obj_t * obj_20 = lv_image_create(root);
        lv_obj_set_pos(obj_20, 0, 0);
        lv_obj_set_size(obj_20, 0, 0);
        lv_image_set_src(obj_20, "A:images/");
        lv_obj_set_style_opa(obj_20, 204, 0);
    }
    {
        lv_obj_t * obj_21 = lv_image_create(root);
        lv_obj_set_pos(obj_21, 0, 0);
        lv_obj_set_size(obj_21, 0, 0);
        lv_image_set_src(obj_21, "A:images/");
        lv_obj_set_style_opa(obj_21, 94, 0);
    }
    {
        lv_obj_t * obj_22 = lv_image_create(root);
        lv_obj_set_pos(obj_22, 0, 0);
        lv_obj_set_size(obj_22, 0, 0);
        lv_image_set_src(obj_22, "A:images/");
        lv_obj_set_style_opa(obj_22, 102, 0);
    }
    {
        lv_obj_t * obj_23 = lv_image_create(root);
        lv_obj_set_pos(obj_23, 0, 0);
        lv_obj_set_size(obj_23, 0, 0);
        lv_image_set_src(obj_23, "A:images/");
        lv_obj_set_style_opa(obj_23, 224, 0);
    }
    {
        lv_obj_t * obj_24 = lv_image_create(root);
        lv_obj_set_pos(obj_24, 0, 0);
        lv_obj_set_size(obj_24, 0, 0);
        lv_image_set_src(obj_24, "A:images/");
        lv_obj_set_style_opa(obj_24, 171, 0);
    }
    {
        lv_obj_t * obj_25 = lv_image_create(root);
        lv_obj_set_pos(obj_25, 0, 0);
        lv_obj_set_size(obj_25, 0, 0);
        lv_image_set_src(obj_25, "A:images/");
        lv_obj_set_style_opa(obj_25, 97, 0);
    }
    {
        lv_obj_t * obj_26 = lv_image_create(root);
        lv_obj_set_pos(obj_26, 0, 0);
        lv_obj_set_size(obj_26, 0, 0);
        lv_image_set_src(obj_26, "A:images/");
        lv_obj_set_style_opa(obj_26, 207, 0);
    }
    {
        lv_obj_t * obj_27 = lv_image_create(root);
        lv_obj_set_pos(obj_27, 0, 0);
        lv_obj_set_size(obj_27, 0, 0);
        lv_image_set_src(obj_27, "A:images/");
        lv_obj_set_style_opa(obj_27, 122, 0);
    }
    {
        lv_obj_t * obj_28 = lv_image_create(root);
        lv_obj_set_pos(obj_28, 0, 0);
        lv_obj_set_size(obj_28, 0, 0);
        lv_image_set_src(obj_28, "A:images/");
        lv_obj_set_style_opa(obj_28, 26, 0);
    }
    {
        lv_obj_t * obj_29 = lv_image_create(root);
        lv_obj_set_pos(obj_29, 0, 0);
        lv_obj_set_size(obj_29, 0, 0);
        lv_image_set_src(obj_29, "A:images/");
        lv_obj_set_style_opa(obj_29, 89, 0);
    }
    {
        lv_obj_t * obj_30 = lv_image_create(root);
        lv_obj_set_pos(obj_30, 0, 0);
        lv_obj_set_size(obj_30, 0, 0);
        lv_image_set_src(obj_30, "A:images/");
        lv_obj_set_style_opa(obj_30, 209, 0);
    }
    {
        lv_obj_t * obj_31 = lv_image_create(root);
        lv_obj_set_pos(obj_31, 0, 0);
        lv_obj_set_size(obj_31, 0, 0);
        lv_image_set_src(obj_31, "A:images/");
        lv_obj_set_style_opa(obj_31, 145, 0);
    }
    {
        lv_obj_t * obj_32 = lv_image_create(root);
        lv_obj_set_pos(obj_32, 0, 0);
        lv_obj_set_size(obj_32, 0, 0);
        lv_image_set_src(obj_32, "A:images/");
        lv_obj_set_style_opa(obj_32, 168, 0);
    }
    {
        lv_obj_t * obj_33 = lv_image_create(root);
        lv_obj_set_pos(obj_33, 0, 0);
        lv_obj_set_size(obj_33, 0, 0);
        lv_image_set_src(obj_33, "A:images/");
        lv_obj_set_style_opa(obj_33, 191, 0);
    }
    {
        lv_obj_t * obj_34 = lv_image_create(root);
        lv_obj_set_pos(obj_34, 0, 0);
        lv_obj_set_size(obj_34, 0, 0);
        lv_image_set_src(obj_34, "A:images/");
        lv_obj_set_style_opa(obj_34, 186, 0);
    }
    {
        lv_obj_t * obj_35 = lv_image_create(root);
        lv_obj_set_pos(obj_35, 0, 0);
        lv_obj_set_size(obj_35, 0, 0);
        lv_image_set_src(obj_35, "A:images/");
        lv_obj_set_style_opa(obj_35, 82, 0);
    }
    {
        lv_obj_t * obj_36 = lv_image_create(root);
        lv_obj_set_pos(obj_36, 0, 0);
        lv_obj_set_size(obj_36, 0, 0);
        lv_image_set_src(obj_36, "A:images/");
        lv_obj_set_style_opa(obj_36, 59, 0);
    }
    {
        lv_obj_t * obj_37 = lv_image_create(root);
        lv_obj_set_pos(obj_37, 0, 0);
        lv_obj_set_size(obj_37, 0, 0);
        lv_image_set_src(obj_37, "A:images/");
        lv_obj_set_style_opa(obj_37, 105, 0);
    }
    {
        lv_obj_t * obj_38 = lv_image_create(root);
        lv_obj_set_pos(obj_38, 0, 0);
        lv_obj_set_size(obj_38, 0, 0);
        lv_image_set_src(obj_38, "A:images/");
        lv_obj_set_style_opa(obj_38, 171, 0);
    }
    {
        lv_obj_t * obj_39 = lv_image_create(root);
        lv_obj_set_pos(obj_39, 0, 0);
        lv_obj_set_size(obj_39, 0, 0);
        lv_image_set_src(obj_39, "A:images/");
        lv_obj_set_style_opa(obj_39, 74, 0);
    }
    {
        lv_obj_t * obj_40 = lv_image_create(root);
        lv_obj_set_pos(obj_40, 0, 0);
        lv_obj_set_size(obj_40, 0, 0);
        lv_image_set_src(obj_40, "A:images/");
        lv_obj_set_style_opa(obj_40, 28, 0);
    }
    {
        lv_obj_t * obj_41 = lv_image_create(root);
        lv_obj_set_pos(obj_41, 0, 0);
        lv_obj_set_size(obj_41, 0, 0);
        lv_image_set_src(obj_41, "A:images/");
        lv_obj_set_style_opa(obj_41, 115, 0);
    }
    {
        lv_obj_t * obj_42 = lv_image_create(root);
        lv_obj_set_pos(obj_42, 0, 0);
        lv_obj_set_size(obj_42, 0, 0);
        lv_image_set_src(obj_42, "A:images/");
        lv_obj_set_style_opa(obj_42, 212, 0);
    }
    {
        lv_obj_t * obj_43 = lv_image_create(root);
        lv_obj_set_pos(obj_43, 0, 0);
        lv_obj_set_size(obj_43, 0, 0);
        lv_image_set_src(obj_43, "A:images/");
        lv_obj_set_style_opa(obj_43, 212, 0);
    }
    {
        lv_obj_t * obj_44 = lv_image_create(root);
        lv_obj_set_pos(obj_44, 0, 0);
        lv_obj_set_size(obj_44, 0, 0);
        lv_image_set_src(obj_44, "A:images/");
        lv_obj_set_style_opa(obj_44, 79, 0);
    }
    {
        lv_obj_t * obj_45 = lv_image_create(root);
        lv_obj_set_pos(obj_45, 0, 0);
        lv_obj_set_size(obj_45, 0, 0);
        lv_image_set_src(obj_45, "A:images/");
        lv_obj_set_style_opa(obj_45, 176, 0);
    }
    {
        lv_obj_t * obj_46 = lv_image_create(root);
        lv_obj_set_pos(obj_46, 0, 0);
        lv_obj_set_size(obj_46, 0, 0);
        lv_image_set_src(obj_46, "A:images/");
        lv_obj_set_style_opa(obj_46, 105, 0);
    }
    {
        lv_obj_t * obj_47 = lv_image_create(root);
        lv_obj_set_pos(obj_47, 0, 0);
        lv_obj_set_size(obj_47, 0, 0);
        lv_image_set_src(obj_47, "A:images/");
        lv_obj_set_style_opa(obj_47, 184, 0);
    }
    {
        lv_obj_t * obj_48 = lv_image_create(root);
        lv_obj_set_pos(obj_48, 0, 0);
        lv_obj_set_size(obj_48, 0, 0);
        lv_image_set_src(obj_48, "A:images/");
        lv_obj_set_style_opa(obj_48, 99, 0);
    }
    {
        lv_obj_t * obj_49 = lv_image_create(root);
        lv_obj_set_pos(obj_49, 0, 0);
        lv_obj_set_size(obj_49, 0, 0);
        lv_image_set_src(obj_49, "A:images/");
        lv_obj_set_style_opa(obj_49, 156, 0);
    }
    {
        lv_obj_t * obj_50 = lv_image_create(root);
        lv_obj_set_pos(obj_50, 0, 0);
        lv_obj_set_size(obj_50, 0, 0);
        lv_image_set_src(obj_50, "A:images/");
        lv_obj_set_style_opa(obj_50, 117, 0);
    }
    return root;
}
