export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        height: 24px;
        text: "";
        width: 135px;
        x: 22px;
        y: 77px;
    }
}
