export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 140px;
        image-fit: contain;
        opacity: 0.701961;
        source: @image-url("images/overlay.png");
        width: 140px;
        x: 30px;
        y: 30px;
    }
}
