export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Rectangle {
        height: 182px;
        width: 182px;
        x: 9px;
        y: 9px;
        Rectangle {
            background: #8000ff;
            border-radius: 90px;
            height: 180px;
            width: 180px;
            x: 1px;
            y: 1px;
        }
    }
}
