/* Generated by Qt PSD Exporter - LVGL C exporter */
#ifndef MAIN_SCREEN_H
#define MAIN_SCREEN_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const int32_t main_screen_width;
extern const int32_t main_screen_height;

/* Create the screen contents as a child of `parent`.
 * Image assets are loaded from "A:images/"; register an LVGL
 * filesystem driver for the 'A' drive letter accordingly. */
lv_obj_t * main_screen_create(lv_obj_t * parent);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* MAIN_SCREEN_H */
