export component MainWindow inherits Window {
    height: 300px;
    title: "";
    width: 400px;
    x: 0px;
    y: 0px;
    Image {
        height: 300px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 400px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        height: 62px;
        text: "";
        width: 226px;
        x: 56px;
        y: 87px;
    }
}
