import 'package:flutter/material.dart';

class MainWindow extends StatelessWidget {
  const MainWindow({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 500,
      width: 500,
      child: Stack(
        children: [
          Positioned(
            height: 500,
            left: 0,
            top: 0,
            width: 500,
            child: Image.asset(
              "assets/images/background.png", 
              fit: BoxFit.contain,
              height: 500,
              width: 500,
            ),
          ),
          Positioned(
            height: 50,
            left: 0,
            top: 0,
            width: 50,
            child: Image.asset(
              "assets/images/l1.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 50,
            top: 0,
            width: 50,
            child: Image.asset(
              "assets/images/l2.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 100,
            top: 0,
            width: 50,
            child: Image.asset(
              "assets/images/l3.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 150,
            top: 0,
            width: 50,
            child: Image.asset(
              "assets/images/l4.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 200,
            top: 0,
            width: 50,
            child: Image.asset(
              "assets/images/l5.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 250,
            top: 0,
            width: 50,
            child: Image.asset(
              "assets/images/l6.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 300,
            top: 0,
            width: 50,
            child: Image.asset(
              "assets/images/l7.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 350,
            top: 0,
            width: 50,
            child: Image.asset(
              "assets/images/l8.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 400,
            top: 0,
            width: 50,
            child: Image.asset(
              "assets/images/l9.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 450,
            top: 0,
            width: 50,
            child: Image.asset(
              "assets/images/l10.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 0,
            top: 50,
            width: 50,
            child: Image.asset(
              "assets/images/l11.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 50,
            top: 50,
            width: 50,
            child: Image.asset(
              "assets/images/l12.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 100,
            top: 50,
            width: 50,
            child: Image.asset(
              "assets/images/l13.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 150,
            top: 50,
            width: 50,
            child: Image.asset(
              "assets/images/l14.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 200,
            top: 50,
            width: 50,
            child: Image.asset(
              "assets/images/l15.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 250,
            top: 50,
            width: 50,
            child: Image.asset(
              "assets/images/l16.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 300,
            top: 50,
            width: 50,
            child: Image.asset(
              "assets/images/l17.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 350,
            top: 50,
            width: 50,
            child: Image.asset(
              "assets/images/l18.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 400,
            top: 50,
            width: 50,
            child: Image.asset(
              "assets/images/l19.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 450,
            top: 50,
            width: 50,
            child: Image.asset(
              "assets/images/l20.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 0,
            top: 100,
            width: 50,
            child: Image.asset(
              "assets/images/l21.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 50,
            top: 100,
            width: 50,
            child: Image.asset(
              "assets/images/l22.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 100,
            top: 100,
            width: 50,
            child: Image.asset(
              "assets/images/l23.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 150,
            top: 100,
            width: 50,
            child: Image.asset(
              "assets/images/l24.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 200,
            top: 100,
            width: 50,
            child: Image.asset(
              "assets/images/l25.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 250,
            top: 100,
            width: 50,
            child: Image.asset(
              "assets/images/l26.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 300,
            top: 100,
            width: 50,
            child: Image.asset(
              "assets/images/l27.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 350,
            top: 100,
            width: 50,
            child: Image.asset(
              "assets/images/l28.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 400,
            top: 100,
            width: 50,
            child: Image.asset(
              "assets/images/l29.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 450,
            top: 100,
            width: 50,
            child: Image.asset(
              "assets/images/l30.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 0,
            top: 150,
            width: 50,
            child: Image.asset(
              "assets/images/l31.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 50,
            top: 150,
            width: 50,
            child: Image.asset(
              "assets/images/l32.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 100,
            top: 150,
            width: 50,
            child: Image.asset(
              "assets/images/l33.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 150,
            top: 150,
            width: 50,
            child: Image.asset(
              "assets/images/l34.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 200,
            top: 150,
            width: 50,
            child: Image.asset(
              "assets/images/l35.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 250,
            top: 150,
            width: 50,
            child: Image.asset(
              "assets/images/l36.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 300,
            top: 150,
            width: 50,
            child: Image.asset(
              "assets/images/l37.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 350,
            top: 150,
            width: 50,
            child: Image.asset(
              "assets/images/l38.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 400,
            top: 150,
            width: 50,
            child: Image.asset(
              "assets/images/l39.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 450,
            top: 150,
            width: 50,
            child: Image.asset(
              "assets/images/l40.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 0,
            top: 200,
            width: 50,
            child: Image.asset(
              "assets/images/l41.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 50,
            top: 200,
            width: 50,
            child: Image.asset(
              "assets/images/l42.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 100,
            top: 200,
            width: 50,
            child: Image.asset(
              "assets/images/l43.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 150,
            top: 200,
            width: 50,
            child: Image.asset(
              "assets/images/l44.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 200,
            top: 200,
            width: 50,
            child: Image.asset(
              "assets/images/l45.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 250,
            top: 200,
            width: 50,
            child: Image.asset(
              "assets/images/l46.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 300,
            top: 200,
            width: 50,
            child: Image.asset(
              "assets/images/l47.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 350,
            top: 200,
            width: 50,
            child: Image.asset(
              "assets/images/l48.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 400,
            top: 200,
            width: 50,
            child: Image.asset(
              "assets/images/l49.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 450,
            top: 200,
            width: 50,
            child: Image.asset(
              "assets/images/l50.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 0,
            top: 250,
            width: 50,
            child: Image.asset(
              "assets/images/l51.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 50,
            top: 250,
            width: 50,
            child: Image.asset(
              "assets/images/l52.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 100,
            top: 250,
            width: 50,
            child: Image.asset(
              "assets/images/l53.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 150,
            top: 250,
            width: 50,
            child: Image.asset(
              "assets/images/l54.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 200,
            top: 250,
            width: 50,
            child: Image.asset(
              "assets/images/l55.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 250,
            top: 250,
            width: 50,
            child: Image.asset(
              "assets/images/l56.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 300,
            top: 250,
            width: 50,
            child: Image.asset(
              "assets/images/l57.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 350,
            top: 250,
            width: 50,
            child: Image.asset(
              "assets/images/l58.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 400,
            top: 250,
            width: 50,
            child: Image.asset(
              "assets/images/l59.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 450,
            top: 250,
            width: 50,
            child: Image.asset(
              "assets/images/l60.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 0,
            top: 300,
            width: 50,
            child: Image.asset(
              "assets/images/l61.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 50,
            top: 300,
            width: 50,
            child: Image.asset(
              "assets/images/l62.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 100,
            top: 300,
            width: 50,
            child: Image.asset(
              "assets/images/l63.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 150,
            top: 300,
            width: 50,
            child: Image.asset(
              "assets/images/l64.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 200,
            top: 300,
            width: 50,
            child: Image.asset(
              "assets/images/l65.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 250,
            top: 300,
            width: 50,
            child: Image.asset(
              "assets/images/l66.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 300,
            top: 300,
            width: 50,
            child: Image.asset(
              "assets/images/l67.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 350,
            top: 300,
            width: 50,
            child: Image.asset(
              "assets/images/l68.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 400,
            top: 300,
            width: 50,
            child: Image.asset(
              "assets/images/l69.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 450,
            top: 300,
            width: 50,
            child: Image.asset(
              "assets/images/l70.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 0,
            top: 350,
            width: 50,
            child: Image.asset(
              "assets/images/l71.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 50,
            top: 350,
            width: 50,
            child: Image.asset(
              "assets/images/l72.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 100,
            top: 350,
            width: 50,
            child: Image.asset(
              "assets/images/l73.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 150,
            top: 350,
            width: 50,
            child: Image.asset(
              "assets/images/l74.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 200,
            top: 350,
            width: 50,
            child: Image.asset(
              "assets/images/l75.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 250,
            top: 350,
            width: 50,
            child: Image.asset(
              "assets/images/l76.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 300,
            top: 350,
            width: 50,
            child: Image.asset(
              "assets/images/l77.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 350,
            top: 350,
            width: 50,
            child: Image.asset(
              "assets/images/l78.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 400,
            top: 350,
            width: 50,
            child: Image.asset(
              "assets/images/l79.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 450,
            top: 350,
            width: 50,
            child: Image.asset(
              "assets/images/l80.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 0,
            top: 400,
            width: 50,
            child: Image.asset(
              "assets/images/l81.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 50,
            top: 400,
            width: 50,
            child: Image.asset(
              "assets/images/l82.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 100,
            top: 400,
            width: 50,
            child: Image.asset(
              "assets/images/l83.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 150,
            top: 400,
            width: 50,
            child: Image.asset(
              "assets/images/l84.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 200,
            top: 400,
            width: 50,
            child: Image.asset(
              "assets/images/l85.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 250,
            top: 400,
            width: 50,
            child: Image.asset(
              "assets/images/l86.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 300,
            top: 400,
            width: 50,
            child: Image.asset(
              "assets/images/l87.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 350,
            top: 400,
            width: 50,
            child: Image.asset(
              "assets/images/l88.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 400,
            top: 400,
            width: 50,
            child: Image.asset(
              "assets/images/l89.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 450,
            top: 400,
            width: 50,
            child: Image.asset(
              "assets/images/l90.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 0,
            top: 450,
            width: 50,
            child: Image.asset(
              "assets/images/l91.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 50,
            top: 450,
            width: 50,
            child: Image.asset(
              "assets/images/l92.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 100,
            top: 450,
            width: 50,
            child: Image.asset(
              "assets/images/l93.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 150,
            top: 450,
            width: 50,
            child: Image.asset(
              "assets/images/l94.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 200,
            top: 450,
            width: 50,
            child: Image.asset(
              "assets/images/l95.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 250,
            top: 450,
            width: 50,
            child: Image.asset(
              "assets/images/l96.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 300,
            top: 450,
            width: 50,
            child: Image.asset(
              "assets/images/l97.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 350,
            top: 450,
            width: 50,
            child: Image.asset(
              "assets/images/l98.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 400,
            top: 450,
            width: 50,
            child: Image.asset(
              "assets/images/l99.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
          Positioned(
            height: 50,
            left: 450,
            top: 450,
            width: 50,
            child: Image.asset(
              "assets/images/l100.png", 
              fit: BoxFit.contain,
              height: 50,
              width: 50,
            ),
          ),
        ],
      ),
    );
  }
}
