export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Rectangle {
        background: transparent;
        border-color: #000000;
        border-width: 4px;
        height: 128px;
        width: 128px;
        x: 36px;
        y: 36px;
        Image {
            height: 120px;
            image-fit: contain;
            source: @image-url("images/stroke_outside.png");
            width: 120px;
            x: 4px;
            y: 4px;
        }
    }
}
