export component MainWindow inherits Window {
    height: 300px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 300px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 213px;
        image-fit: contain;
        source: @image-url("images/rotated.png");
        width: 212px;
        x: 44px;
        y: 44px;
    }
}
