export component MainWindow inherits Window {
    height: 300px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 300px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Sans Serif";
        font-size: 9px;
        height: 22px;
        horizontal-alignment: left;
        text: "";
        width: 40px;
        x: 100px;
        y: 33px;
    }
    Text {
        color: #000000;
        font-family: "Sans Serif";
        font-size: 9px;
        height: 19px;
        horizontal-alignment: left;
        text: "";
        width: 70px;
        x: 102px;
        y: 132px;
    }
    Text {
        color: #000000;
        font-family: "Sans Serif";
        font-size: 9px;
        height: 18px;
        horizontal-alignment: left;
        text: "";
        width: 76px;
        x: 102px;
        y: 233px;
    }
}
