export component MainWindow inherits Window {
    height: 1920px;
    title: "";
    width: 1080px;
    x: 0px;
    y: 0px;
    Image {
        height: 1920px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 1080px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Sans Serif";
        font-size: 9px;
        height: 36px;
        horizontal-alignment: left;
        text: "";
        width: 154px;
        x: 404px;
        y: 925px;
    }
}
