export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Rectangle {
        height: 152px;
        width: 152px;
        x: 24px;
        y: 24px;
        Rectangle {
            background: #00b400;
            height: 150px;
            width: 150px;
            x: 1px;
            y: 1px;
        }
    }
}
