export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #c83232;
        font-family: "Roboto";
        font-size: 48px;
        height: 63px;
        horizontal-alignment: left;
        stroke: #bf000000;
        stroke-width: 2px;
        text: "STYLED";
        width: 173px;
        x: 20px;
        y: 90px;
    }
}
