export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Rectangle {
        background: transparent;
        height: 63px;
        width: 173px;
        x: 20px;
        y: 90px;
        Text {
            color: #000000bf;
            font-family: "Roboto";
            font-size: 48px;
            height: 100%;
            horizontal-alignment: left;
            overflow: clip;
            text: "STYLED";
            vertical-alignment: bottom;
            width: 100%;
            x: 2px;
            y: 4px;
        }
        Text {
            color: #c83232;
            font-family: "Roboto";
            font-size: 48px;
            height: 100%;
            horizontal-alignment: left;
            overflow: clip;
            text: "STYLED";
            vertical-alignment: bottom;
            width: 100%;
        }
    }
}
