export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 38px;
        image-fit: contain;
        source: @image-url("images/squeeze.png");
        width: 130px;
        x: 64px;
        y: 90px;
    }
}
