export component MainWindow inherits Window {
    height: 1px;
    title: "";
    width: 1px;
    x: 0px;
    y: 0px;
    Image {
        height: 1px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 1px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 1px;
        image-fit: contain;
        source: @image-url("images/pixel.png");
        width: 1px;
        x: 0px;
        y: 0px;
    }
}
