export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Sans Serif";
        font-size: 9px;
        height: 37px;
        horizontal-alignment: left;
        text: "";
        width: 167px;
        x: 34px;
        y: 64px;
    }
}
