export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Roboto";
        font-size: 14px;
        height: 151px;
        horizontal-alignment: left;
        text: "This is justified text that should wrap across multiple lines in a text box.";
        width: 253px;
        x: 25px;
        y: 24px;
    }
}
