export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/dark_bg.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Rectangle {
        background: transparent;
        height: 48px;
        width: 129px;
        x: 30px;
        y: 82px;
        Text {
            color: #000000e6;
            font-family: "Roboto";
            font-size: 36px;
            font-weight: 700;
            height: 100%;
            horizontal-alignment: left;
            text: "Shadow";
            vertical-alignment: bottom;
            width: 100%;
            x: 3px;
            y: 3px;
        }
        Text {
            color: #ffffff;
            font-family: "Roboto";
            font-size: 36px;
            font-weight: 700;
            height: 100%;
            horizontal-alignment: left;
            text: "Shadow";
            vertical-alignment: bottom;
            width: 100%;
        }
    }
}
