export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/dark_bg.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #ffffff;
        font-family: "Roboto";
        font-size: 36px;
        height: 48px;
        horizontal-alignment: left;
        stroke: #e6000000;
        stroke-width: 2px;
        text: "Shadow";
        width: 129px;
        x: 30px;
        y: 82px;
    }
}
