export component MainWindow inherits Window {
    height: 300px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 300px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 100px;
        image-fit: contain;
        source: @image-url("images/scaled.png");
        width: 100px;
        x: 100px;
        y: 100px;
    }
}
