export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Rectangle {
        height: 200px;
        width: 300px;
        x: 0px;
        y: 0px;
        Rectangle {
            background: #000000;
            height: 200px;
            width: 300px;
            x: 0px;
            y: 0px;
        }
    }
    Text {
        color: #ffffff;
        font-family: "Roboto";
        font-size: 36px;
        height: 48px;
        horizontal-alignment: left;
        text: "White Text";
        vertical-alignment: bottom;
        width: 168px;
        x: 50px;
        y: 82px;
    }
}
