export component MainWindow inherits Window {
    height: 300px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 300px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #ff0000;
        font-family: "Roboto";
        font-size: 14px;
        height: 20px;
        horizontal-alignment: left;
        text: "Layer 1";
        vertical-alignment: bottom;
        width: 45px;
        x: 10px;
        y: 4px;
    }
    Text {
        color: #00ff00;
        font-family: "Roboto";
        font-size: 14px;
        height: 20px;
        horizontal-alignment: left;
        text: "Layer 2";
        vertical-alignment: bottom;
        width: 45px;
        x: 10px;
        y: 29px;
    }
    Text {
        color: #0000ff;
        font-family: "Roboto";
        font-size: 14px;
        height: 20px;
        horizontal-alignment: left;
        text: "Layer 3";
        vertical-alignment: bottom;
        width: 45px;
        x: 10px;
        y: 54px;
    }
    Text {
        color: #ff8000;
        font-family: "Roboto";
        font-size: 14px;
        height: 20px;
        horizontal-alignment: left;
        text: "Layer 4";
        vertical-alignment: bottom;
        width: 45px;
        x: 10px;
        y: 79px;
    }
    Text {
        color: #8000ff;
        font-family: "Roboto";
        font-size: 14px;
        height: 20px;
        horizontal-alignment: left;
        text: "Layer 5";
        vertical-alignment: bottom;
        width: 45px;
        x: 10px;
        y: 104px;
    }
    Text {
        color: #008080;
        font-family: "Roboto";
        font-size: 14px;
        height: 20px;
        horizontal-alignment: left;
        text: "Layer 6";
        vertical-alignment: bottom;
        width: 45px;
        x: 10px;
        y: 129px;
    }
    Text {
        color: #808000;
        font-family: "Roboto";
        font-size: 14px;
        height: 20px;
        horizontal-alignment: left;
        text: "Layer 7";
        vertical-alignment: bottom;
        width: 45px;
        x: 10px;
        y: 154px;
    }
    Text {
        color: #404040;
        font-family: "Roboto";
        font-size: 14px;
        height: 20px;
        horizontal-alignment: left;
        text: "Layer 8";
        vertical-alignment: bottom;
        width: 45px;
        x: 10px;
        y: 179px;
    }
    Text {
        color: #c000c0;
        font-family: "Roboto";
        font-size: 14px;
        height: 20px;
        horizontal-alignment: left;
        text: "Layer 9";
        vertical-alignment: bottom;
        width: 45px;
        x: 10px;
        y: 204px;
    }
    Text {
        color: #00c000;
        font-family: "Roboto";
        font-size: 14px;
        height: 20px;
        horizontal-alignment: left;
        text: "Layer 10";
        vertical-alignment: bottom;
        width: 53px;
        x: 10px;
        y: 229px;
    }
}
