export component MainWindow inherits Window {
    height: 300px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 300px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Sans Serif";
        font-size: 9px;
        height: 13px;
        horizontal-alignment: left;
        text: "";
        width: 42px;
        x: 11px;
        y: 10px;
    }
    Text {
        color: #000000;
        font-family: "Sans Serif";
        font-size: 9px;
        height: 13px;
        horizontal-alignment: left;
        text: "";
        width: 44px;
        x: 11px;
        y: 35px;
    }
    Text {
        color: #000000;
        font-family: "Sans Serif";
        font-size: 9px;
        height: 13px;
        horizontal-alignment: left;
        text: "";
        width: 44px;
        x: 11px;
        y: 60px;
    }
    Text {
        color: #000000;
        font-family: "Sans Serif";
        font-size: 9px;
        height: 13px;
        horizontal-alignment: left;
        text: "";
        width: 44px;
        x: 11px;
        y: 85px;
    }
    Text {
        color: #000000;
        font-family: "Sans Serif";
        font-size: 9px;
        height: 13px;
        horizontal-alignment: left;
        text: "";
        width: 44px;
        x: 11px;
        y: 110px;
    }
    Text {
        color: #000000;
        font-family: "Sans Serif";
        font-size: 9px;
        height: 13px;
        horizontal-alignment: left;
        text: "";
        width: 44px;
        x: 11px;
        y: 135px;
    }
    Text {
        color: #000000;
        font-family: "Sans Serif";
        font-size: 9px;
        height: 13px;
        horizontal-alignment: left;
        text: "";
        width: 44px;
        x: 11px;
        y: 160px;
    }
    Text {
        color: #000000;
        font-family: "Sans Serif";
        font-size: 9px;
        height: 13px;
        horizontal-alignment: left;
        text: "";
        width: 44px;
        x: 11px;
        y: 185px;
    }
    Text {
        color: #000000;
        font-family: "Sans Serif";
        font-size: 9px;
        height: 13px;
        horizontal-alignment: left;
        text: "";
        width: 44px;
        x: 11px;
        y: 210px;
    }
    Text {
        color: #000000;
        font-family: "Sans Serif";
        font-size: 9px;
        height: 13px;
        horizontal-alignment: left;
        text: "";
        width: 51px;
        x: 11px;
        y: 235px;
    }
}
