export component MainWindow inherits Window {
    height: 300px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 300px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Text {
        clip: true;
        color: #ff0000;
        font-family: "Roboto";
        font-size: 14px;
        height: 19px;
        horizontal-alignment: left;
        text: "Layer 1";
        vertical-alignment: bottom;
        width: 45px;
        x: 10px;
        y: 5px;
    }
    Text {
        clip: true;
        color: #00ff00;
        font-family: "Roboto";
        font-size: 14px;
        height: 19px;
        horizontal-alignment: left;
        text: "Layer 2";
        vertical-alignment: bottom;
        width: 45px;
        x: 10px;
        y: 30px;
    }
    Text {
        clip: true;
        color: #0000ff;
        font-family: "Roboto";
        font-size: 14px;
        height: 19px;
        horizontal-alignment: left;
        text: "Layer 3";
        vertical-alignment: bottom;
        width: 45px;
        x: 10px;
        y: 55px;
    }
    Text {
        clip: true;
        color: #ff8000;
        font-family: "Roboto";
        font-size: 14px;
        height: 19px;
        horizontal-alignment: left;
        text: "Layer 4";
        vertical-alignment: bottom;
        width: 45px;
        x: 10px;
        y: 80px;
    }
    Text {
        clip: true;
        color: #8000ff;
        font-family: "Roboto";
        font-size: 14px;
        height: 19px;
        horizontal-alignment: left;
        text: "Layer 5";
        vertical-alignment: bottom;
        width: 45px;
        x: 10px;
        y: 105px;
    }
    Text {
        clip: true;
        color: #008080;
        font-family: "Roboto";
        font-size: 14px;
        height: 19px;
        horizontal-alignment: left;
        text: "Layer 6";
        vertical-alignment: bottom;
        width: 45px;
        x: 10px;
        y: 130px;
    }
    Text {
        clip: true;
        color: #808000;
        font-family: "Roboto";
        font-size: 14px;
        height: 19px;
        horizontal-alignment: left;
        text: "Layer 7";
        vertical-alignment: bottom;
        width: 45px;
        x: 10px;
        y: 155px;
    }
    Text {
        clip: true;
        color: #404040;
        font-family: "Roboto";
        font-size: 14px;
        height: 19px;
        horizontal-alignment: left;
        text: "Layer 8";
        vertical-alignment: bottom;
        width: 45px;
        x: 10px;
        y: 180px;
    }
    Text {
        clip: true;
        color: #c000c0;
        font-family: "Roboto";
        font-size: 14px;
        height: 19px;
        horizontal-alignment: left;
        text: "Layer 9";
        vertical-alignment: bottom;
        width: 45px;
        x: 10px;
        y: 205px;
    }
    Text {
        clip: true;
        color: #00c000;
        font-family: "Roboto";
        font-size: 14px;
        height: 19px;
        horizontal-alignment: left;
        text: "Layer 10";
        vertical-alignment: bottom;
        width: 53px;
        x: 10px;
        y: 230px;
    }
}
