export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 142px;
        image-fit: contain;
        source: @image-url("images/gradient_shape.png");
        width: 142px;
        x: 29px;
        y: 29px;
    }
}
