export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 27px;
        image-fit: contain;
        source: @image-url("images/twist.png");
        width: 108px;
        x: 51px;
        y: 94px;
    }
}
