export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 120px;
        image-fit: contain;
        source: @image-url("images/clip_base.png");
        width: 120px;
        x: 40px;
        y: 40px;
    }
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/clipped_1.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 100px;
        image-fit: contain;
        source: @image-url("images/clipped_2.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
}
