/* Generated by Qt PSD Exporter - LVGL C exporter */
#include "main_screen.h"

const int32_t main_screen_width = 200;
const int32_t main_screen_height = 200;

lv_obj_t * main_screen_create(lv_obj_t * parent)
{
    lv_obj_t * root = lv_obj_create(parent);
    lv_obj_set_pos(root, 0, 0);
    lv_obj_set_size(root, 200, 200);
    lv_obj_set_style_pad_all(root, 0, 0);
    lv_obj_set_style_border_width(root, 0, 0);
    lv_obj_set_style_radius(root, 0, 0);
    lv_obj_set_style_bg_opa(root, 0, 0);
    lv_obj_set_scrollbar_mode(root, LV_SCROLLBAR_MODE_OFF);
    {
        lv_obj_t * obj_0 = lv_image_create(root);
        lv_obj_set_pos(obj_0, 0, 0);
        lv_obj_set_size(obj_0, 200, 200);
        lv_image_set_src(obj_0, "A:images/background.png");
    }
    {
        lv_obj_t * obj_1 = lv_image_create(root);
        lv_obj_set_pos(obj_1, 0, 0);
        lv_obj_set_size(obj_1, 200, 50);
        lv_image_set_src(obj_1, "A:images/d953ee13be5cbb46.png");
    }
    {
        lv_obj_t * obj_2 = lv_image_create(root);
        lv_obj_set_pos(obj_2, 0, 50);
        lv_obj_set_size(obj_2, 200, 50);
        lv_image_set_src(obj_2, "A:images/471b942182a4e41b.png");
    }
    {
        lv_obj_t * obj_3 = lv_image_create(root);
        lv_obj_set_pos(obj_3, 0, 100);
        lv_obj_set_size(obj_3, 200, 50);
        lv_image_set_src(obj_3, "A:images/4b3d9f4f6e50544b.png");
    }
    {
        lv_obj_t * obj_4 = lv_image_create(root);
        lv_obj_set_pos(obj_4, 0, 150);
        lv_obj_set_size(obj_4, 200, 50);
        lv_image_set_src(obj_4, "A:images/668aa0e7340f06f7.png");
    }
    return root;
}
