/* Generated by Qt PSD Exporter - LVGL C exporter */
#include "main_screen.h"

const int32_t main_screen_width = 400;
const int32_t main_screen_height = 300;

lv_obj_t * main_screen_create(lv_obj_t * parent)
{
    lv_obj_t * root = lv_obj_create(parent);
    lv_obj_set_pos(root, 0, 0);
    lv_obj_set_size(root, 400, 300);
    lv_obj_set_style_pad_all(root, 0, 0);
    lv_obj_set_style_border_width(root, 0, 0);
    lv_obj_set_style_radius(root, 0, 0);
    lv_obj_set_style_bg_opa(root, 0, 0);
    lv_obj_set_scrollbar_mode(root, LV_SCROLLBAR_MODE_OFF);
    {
        lv_obj_t * obj_0 = lv_image_create(root);
        lv_obj_set_pos(obj_0, 0, 0);
        lv_obj_set_size(obj_0, 400, 300);
        lv_image_set_src(obj_0, "A:images/background.png");
    }
    {
        lv_obj_t * obj_1 = lv_image_create(root);
        lv_obj_set_pos(obj_1, 0, 0);
        lv_obj_set_size(obj_1, 400, 300);
        lv_image_set_src(obj_1, "A:images/bg_color.png");
    }
    {
        lv_obj_t * obj_2 = lv_obj_create(root);
        lv_obj_set_pos(obj_2, 49, 29);
        lv_obj_set_size(obj_2, 302, 242);
        lv_obj_set_style_bg_color(obj_2, lv_color_hex(0xffffff), 0);
        lv_obj_set_style_bg_opa(obj_2, 255, 0);
        lv_obj_set_style_border_width(obj_2, 0, 0);
    }
    {
        lv_obj_t * obj_3 = lv_label_create(root);
        lv_obj_set_pos(obj_3, 80, 57);
        lv_obj_set_size(obj_3, 87, 29);
        lv_obj_set_style_text_align(obj_3, LV_TEXT_ALIGN_LEFT, 0);
        lv_obj_set_style_text_color(obj_3, lv_color_hex(0x1e1e1e), 0);
        lv_obj_set_style_text_font(obj_3, &lv_font_montserrat_20, 0);
        lv_label_set_text(obj_3, "Card Title");
    }
    {
        lv_obj_t * obj_4 = lv_label_create(root);
        lv_obj_set_pos(obj_4, 80, 109);
        lv_obj_set_size(obj_4, 250, 121);
        lv_obj_set_style_text_align(obj_4, LV_TEXT_ALIGN_LEFT, 0);
        lv_obj_set_style_text_color(obj_4, lv_color_hex(0x505050), 0);
        lv_obj_set_style_text_font(obj_4, &lv_font_montserrat_12, 0);
        lv_label_set_text(obj_4, "This is body text in a card layout with multiple layers and groups.");
    }
    return root;
}
