export component MainWindow inherits Window {
    height: 500px;
    title: "";
    width: 500px;
    x: 0px;
    y: 0px;
    Image {
        height: 500px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 500px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        height: 20px;
        text: "";
        width: 65px;
        x: 301px;
        y: 381px;
    }
}
