export component MainWindow inherits Window {
    height: 500px;
    title: "";
    width: 500px;
    x: 0px;
    y: 0px;
    Image {
        height: 500px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 500px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Roboto";
        font-size: 24px;
        height: 32px;
        horizontal-alignment: left;
        text: "Offset";
        width: 66px;
        x: 300px;
        y: 375px;
    }
}
