/* Generated by Qt PSD Exporter - LVGL C exporter */
#include "main_screen.h"

const int32_t main_screen_width = 300;
const int32_t main_screen_height = 200;

lv_obj_t * main_screen_create(lv_obj_t * parent)
{
    lv_obj_t * root = lv_obj_create(parent);
    lv_obj_set_pos(root, 0, 0);
    lv_obj_set_size(root, 300, 200);
    lv_obj_set_style_pad_all(root, 0, 0);
    lv_obj_set_style_border_width(root, 0, 0);
    lv_obj_set_style_radius(root, 0, 0);
    lv_obj_set_style_bg_opa(root, 0, 0);
    lv_obj_set_scrollbar_mode(root, LV_SCROLLBAR_MODE_OFF);
    {
        lv_obj_t * obj_0 = lv_image_create(root);
        lv_obj_set_pos(obj_0, 0, 0);
        lv_obj_set_size(obj_0, 300, 200);
        lv_image_set_src(obj_0, "A:images/background.png");
    }
    {
        lv_obj_t * obj_1 = lv_image_create(root);
        lv_obj_set_pos(obj_1, 0, 0);
        lv_obj_set_size(obj_1, 60, 200);
        lv_image_set_src(obj_1, "A:images/layer_1.png");
    }
    {
        lv_obj_t * obj_2 = lv_image_create(root);
        lv_obj_set_pos(obj_2, 60, 0);
        lv_obj_set_size(obj_2, 60, 200);
        lv_image_set_src(obj_2, "A:images/layer_2.png");
    }
    {
        lv_obj_t * obj_3 = lv_image_create(root);
        lv_obj_set_pos(obj_3, 120, 0);
        lv_obj_set_size(obj_3, 60, 200);
        lv_image_set_src(obj_3, "A:images/layer_3.png");
    }
    {
        lv_obj_t * obj_4 = lv_image_create(root);
        lv_obj_set_pos(obj_4, 180, 0);
        lv_obj_set_size(obj_4, 60, 200);
        lv_image_set_src(obj_4, "A:images/layer_4.png");
    }
    {
        lv_obj_t * obj_5 = lv_image_create(root);
        lv_obj_set_pos(obj_5, 240, 0);
        lv_obj_set_size(obj_5, 60, 200);
        lv_image_set_src(obj_5, "A:images/layer_5.png");
    }
    return root;
}
