/* Generated by Qt PSD Exporter - LVGL C exporter */
#include "main_screen.h"

const int32_t main_screen_width = 320;
const int32_t main_screen_height = 240;

lv_obj_t * main_screen_create(lv_obj_t * parent)
{
    lv_obj_t * root = lv_obj_create(parent);
    lv_obj_set_pos(root, 0, 0);
    lv_obj_set_size(root, 320, 240);
    lv_obj_set_style_pad_all(root, 0, 0);
    lv_obj_set_style_border_width(root, 0, 0);
    lv_obj_set_style_radius(root, 0, 0);
    lv_obj_set_style_bg_opa(root, 0, 0);
    lv_obj_set_scrollbar_mode(root, LV_SCROLLBAR_MODE_OFF);
    {
        lv_obj_t * obj_0 = lv_obj_create(root);
        lv_obj_set_pos(obj_0, 0, 0);
        lv_obj_set_size(obj_0, 320, 240);
        lv_obj_set_style_bg_color(obj_0, lv_color_hex(0xf7e790), 0);
        lv_obj_set_style_bg_opa(obj_0, 255, 0);
    }
    {
        lv_obj_t * obj_1 = lv_obj_create(root);
        lv_obj_set_pos(obj_1, 39, 49);
        lv_obj_set_size(obj_1, 182, 52);
        lv_obj_set_style_bg_color(obj_1, lv_color_hex(0xd4f5c9), 0);
        lv_obj_set_style_bg_opa(obj_1, 255, 0);
        lv_obj_set_style_border_width(obj_1, 0, 0);
        lv_obj_set_style_radius(obj_1, 20, 0);
    }
    {
        lv_obj_t * obj_2 = lv_obj_create(root);
        lv_obj_set_pos(obj_2, 72, 89);
        lv_obj_set_size(obj_2, 139, 13);
        lv_obj_set_style_bg_color(obj_2, lv_color_hex(0x217903), 0);
        lv_obj_set_style_bg_opa(obj_2, 255, 0);
        lv_obj_set_style_border_width(obj_2, 0, 0);
    }
    {
        lv_obj_t * obj_3 = lv_obj_create(root);
        lv_obj_set_pos(obj_3, 79, 81);
        lv_obj_set_size(obj_3, 25, 14);
        lv_obj_set_style_bg_color(obj_3, lv_color_hex(0x5e88e7), 0);
        lv_obj_set_style_bg_opa(obj_3, 255, 0);
        lv_obj_set_style_border_width(obj_3, 0, 0);
    }
    {
        lv_obj_t * obj_4 = lv_label_create(root);
        lv_obj_set_pos(obj_4, 50, 54);
        lv_obj_set_size(obj_4, 160, 44);
        lv_obj_set_style_text_align(obj_4, LV_TEXT_ALIGN_CENTER, 0);
        lv_obj_set_style_text_color(obj_4, lv_color_hex(0x000000), 0);
        lv_obj_set_style_text_font(obj_4, &lv_font_montserrat_30, 0);
        lv_label_set_text(obj_4, "Example1");
    }
    {
        lv_obj_t * obj_5 = lv_obj_create(root);
        lv_obj_set_pos(obj_5, 39, 134);
        lv_obj_set_size(obj_5, 182, 52);
        lv_obj_set_style_bg_color(obj_5, lv_color_hex(0xd4f5c9), 0);
        lv_obj_set_style_bg_opa(obj_5, 255, 0);
        lv_obj_set_style_border_width(obj_5, 0, 0);
        lv_obj_set_style_radius(obj_5, 20, 0);
    }
    {
        lv_obj_t * obj_6 = lv_obj_create(root);
        lv_obj_set_pos(obj_6, 72, 174);
        lv_obj_set_size(obj_6, 139, 12);
        lv_obj_set_style_bg_color(obj_6, lv_color_hex(0x217903), 0);
        lv_obj_set_style_bg_opa(obj_6, 255, 0);
        lv_obj_set_style_border_width(obj_6, 0, 0);
    }
    {
        lv_obj_t * obj_7 = lv_obj_create(root);
        lv_obj_set_pos(obj_7, 179, 166);
        lv_obj_set_size(obj_7, 25, 14);
        lv_obj_set_style_bg_color(obj_7, lv_color_hex(0x5e88e7), 0);
        lv_obj_set_style_bg_opa(obj_7, 255, 0);
        lv_obj_set_style_border_width(obj_7, 0, 0);
    }
    {
        lv_obj_t * obj_8 = lv_label_create(root);
        lv_obj_set_pos(obj_8, 50, 134);
        lv_obj_set_size(obj_8, 160, 44);
        lv_obj_set_style_text_align(obj_8, LV_TEXT_ALIGN_CENTER, 0);
        lv_obj_set_style_text_color(obj_8, lv_color_hex(0x000000), 0);
        lv_obj_set_style_text_font(obj_8, &lv_font_montserrat_30, 0);
        lv_label_set_text(obj_8, "Example1");
    }
    return root;
}
