/* Generated by Qt PSD Exporter - LVGL C exporter */
#include "main_screen.h"

const int32_t main_screen_width = 300;
const int32_t main_screen_height = 300;

lv_obj_t * main_screen_create(lv_obj_t * parent)
{
    lv_obj_t * root = lv_obj_create(parent);
    lv_obj_set_pos(root, 0, 0);
    lv_obj_set_size(root, 300, 300);
    lv_obj_set_style_pad_all(root, 0, 0);
    lv_obj_set_style_border_width(root, 0, 0);
    lv_obj_set_style_radius(root, 0, 0);
    lv_obj_set_style_bg_opa(root, 0, 0);
    lv_obj_set_scrollbar_mode(root, LV_SCROLLBAR_MODE_OFF);
    {
        lv_obj_t * obj_0 = lv_image_create(root);
        lv_obj_set_pos(obj_0, 0, 0);
        lv_obj_set_size(obj_0, 300, 300);
        lv_image_set_src(obj_0, "A:images/background.png");
    }
    {
        lv_obj_t * obj_1 = lv_label_create(root);
        lv_obj_set_pos(obj_1, 10, 4);
        lv_obj_set_size(obj_1, 45, 20);
        lv_obj_set_style_text_align(obj_1, LV_TEXT_ALIGN_LEFT, 0);
        lv_obj_set_style_text_color(obj_1, lv_color_hex(0xff0000), 0);
        lv_obj_set_style_text_font(obj_1, &lv_font_montserrat_14, 0);
        lv_label_set_text(obj_1, "Layer 1");
    }
    {
        lv_obj_t * obj_2 = lv_label_create(root);
        lv_obj_set_pos(obj_2, 10, 29);
        lv_obj_set_size(obj_2, 45, 20);
        lv_obj_set_style_text_align(obj_2, LV_TEXT_ALIGN_LEFT, 0);
        lv_obj_set_style_text_color(obj_2, lv_color_hex(0x00ff00), 0);
        lv_obj_set_style_text_font(obj_2, &lv_font_montserrat_14, 0);
        lv_label_set_text(obj_2, "Layer 2");
    }
    {
        lv_obj_t * obj_3 = lv_label_create(root);
        lv_obj_set_pos(obj_3, 10, 54);
        lv_obj_set_size(obj_3, 45, 20);
        lv_obj_set_style_text_align(obj_3, LV_TEXT_ALIGN_LEFT, 0);
        lv_obj_set_style_text_color(obj_3, lv_color_hex(0x0000ff), 0);
        lv_obj_set_style_text_font(obj_3, &lv_font_montserrat_14, 0);
        lv_label_set_text(obj_3, "Layer 3");
    }
    {
        lv_obj_t * obj_4 = lv_label_create(root);
        lv_obj_set_pos(obj_4, 10, 79);
        lv_obj_set_size(obj_4, 45, 20);
        lv_obj_set_style_text_align(obj_4, LV_TEXT_ALIGN_LEFT, 0);
        lv_obj_set_style_text_color(obj_4, lv_color_hex(0xff8000), 0);
        lv_obj_set_style_text_font(obj_4, &lv_font_montserrat_14, 0);
        lv_label_set_text(obj_4, "Layer 4");
    }
    {
        lv_obj_t * obj_5 = lv_label_create(root);
        lv_obj_set_pos(obj_5, 10, 104);
        lv_obj_set_size(obj_5, 45, 20);
        lv_obj_set_style_text_align(obj_5, LV_TEXT_ALIGN_LEFT, 0);
        lv_obj_set_style_text_color(obj_5, lv_color_hex(0x8000ff), 0);
        lv_obj_set_style_text_font(obj_5, &lv_font_montserrat_14, 0);
        lv_label_set_text(obj_5, "Layer 5");
    }
    {
        lv_obj_t * obj_6 = lv_label_create(root);
        lv_obj_set_pos(obj_6, 10, 129);
        lv_obj_set_size(obj_6, 45, 20);
        lv_obj_set_style_text_align(obj_6, LV_TEXT_ALIGN_LEFT, 0);
        lv_obj_set_style_text_color(obj_6, lv_color_hex(0x008080), 0);
        lv_obj_set_style_text_font(obj_6, &lv_font_montserrat_14, 0);
        lv_label_set_text(obj_6, "Layer 6");
    }
    {
        lv_obj_t * obj_7 = lv_label_create(root);
        lv_obj_set_pos(obj_7, 10, 154);
        lv_obj_set_size(obj_7, 45, 20);
        lv_obj_set_style_text_align(obj_7, LV_TEXT_ALIGN_LEFT, 0);
        lv_obj_set_style_text_color(obj_7, lv_color_hex(0x808000), 0);
        lv_obj_set_style_text_font(obj_7, &lv_font_montserrat_14, 0);
        lv_label_set_text(obj_7, "Layer 7");
    }
    {
        lv_obj_t * obj_8 = lv_label_create(root);
        lv_obj_set_pos(obj_8, 10, 179);
        lv_obj_set_size(obj_8, 45, 20);
        lv_obj_set_style_text_align(obj_8, LV_TEXT_ALIGN_LEFT, 0);
        lv_obj_set_style_text_color(obj_8, lv_color_hex(0x404040), 0);
        lv_obj_set_style_text_font(obj_8, &lv_font_montserrat_14, 0);
        lv_label_set_text(obj_8, "Layer 8");
    }
    {
        lv_obj_t * obj_9 = lv_label_create(root);
        lv_obj_set_pos(obj_9, 10, 204);
        lv_obj_set_size(obj_9, 45, 20);
        lv_obj_set_style_text_align(obj_9, LV_TEXT_ALIGN_LEFT, 0);
        lv_obj_set_style_text_color(obj_9, lv_color_hex(0xc000c0), 0);
        lv_obj_set_style_text_font(obj_9, &lv_font_montserrat_14, 0);
        lv_label_set_text(obj_9, "Layer 9");
    }
    {
        lv_obj_t * obj_10 = lv_label_create(root);
        lv_obj_set_pos(obj_10, 10, 229);
        lv_obj_set_size(obj_10, 53, 20);
        lv_obj_set_style_text_align(obj_10, LV_TEXT_ALIGN_LEFT, 0);
        lv_obj_set_style_text_color(obj_10, lv_color_hex(0x00c000), 0);
        lv_obj_set_style_text_font(obj_10, &lv_font_montserrat_14, 0);
        lv_label_set_text(obj_10, "Layer 10");
    }
    return root;
}
