/* Generated by Qt PSD Exporter - LVGL C exporter */
#include "main_screen.h"

const int32_t main_screen_width = 500;
const int32_t main_screen_height = 500;

lv_obj_t * main_screen_create(lv_obj_t * parent)
{
    lv_obj_t * root = lv_obj_create(parent);
    lv_obj_set_pos(root, 0, 0);
    lv_obj_set_size(root, 500, 500);
    lv_obj_set_style_pad_all(root, 0, 0);
    lv_obj_set_style_border_width(root, 0, 0);
    lv_obj_set_style_radius(root, 0, 0);
    lv_obj_set_style_bg_opa(root, 0, 0);
    lv_obj_set_scrollbar_mode(root, LV_SCROLLBAR_MODE_OFF);
    {
        lv_obj_t * obj_0 = lv_image_create(root);
        lv_obj_set_pos(obj_0, 0, 0);
        lv_obj_set_size(obj_0, 500, 500);
        lv_image_set_src(obj_0, "A:images/background.png");
    }
    {
        lv_obj_t * obj_1 = lv_image_create(root);
        lv_obj_set_pos(obj_1, 0, 0);
        lv_obj_set_size(obj_1, 50, 50);
        lv_image_set_src(obj_1, "A:images/l1.png");
    }
    {
        lv_obj_t * obj_2 = lv_image_create(root);
        lv_obj_set_pos(obj_2, 50, 0);
        lv_obj_set_size(obj_2, 50, 50);
        lv_image_set_src(obj_2, "A:images/l2.png");
    }
    {
        lv_obj_t * obj_3 = lv_image_create(root);
        lv_obj_set_pos(obj_3, 100, 0);
        lv_obj_set_size(obj_3, 50, 50);
        lv_image_set_src(obj_3, "A:images/l3.png");
    }
    {
        lv_obj_t * obj_4 = lv_image_create(root);
        lv_obj_set_pos(obj_4, 150, 0);
        lv_obj_set_size(obj_4, 50, 50);
        lv_image_set_src(obj_4, "A:images/l4.png");
    }
    {
        lv_obj_t * obj_5 = lv_image_create(root);
        lv_obj_set_pos(obj_5, 200, 0);
        lv_obj_set_size(obj_5, 50, 50);
        lv_image_set_src(obj_5, "A:images/l5.png");
    }
    {
        lv_obj_t * obj_6 = lv_image_create(root);
        lv_obj_set_pos(obj_6, 250, 0);
        lv_obj_set_size(obj_6, 50, 50);
        lv_image_set_src(obj_6, "A:images/l6.png");
    }
    {
        lv_obj_t * obj_7 = lv_image_create(root);
        lv_obj_set_pos(obj_7, 300, 0);
        lv_obj_set_size(obj_7, 50, 50);
        lv_image_set_src(obj_7, "A:images/l7.png");
    }
    {
        lv_obj_t * obj_8 = lv_image_create(root);
        lv_obj_set_pos(obj_8, 350, 0);
        lv_obj_set_size(obj_8, 50, 50);
        lv_image_set_src(obj_8, "A:images/l8.png");
    }
    {
        lv_obj_t * obj_9 = lv_image_create(root);
        lv_obj_set_pos(obj_9, 400, 0);
        lv_obj_set_size(obj_9, 50, 50);
        lv_image_set_src(obj_9, "A:images/l9.png");
    }
    {
        lv_obj_t * obj_10 = lv_image_create(root);
        lv_obj_set_pos(obj_10, 450, 0);
        lv_obj_set_size(obj_10, 50, 50);
        lv_image_set_src(obj_10, "A:images/l10.png");
    }
    {
        lv_obj_t * obj_11 = lv_image_create(root);
        lv_obj_set_pos(obj_11, 0, 50);
        lv_obj_set_size(obj_11, 50, 50);
        lv_image_set_src(obj_11, "A:images/l11.png");
    }
    {
        lv_obj_t * obj_12 = lv_image_create(root);
        lv_obj_set_pos(obj_12, 50, 50);
        lv_obj_set_size(obj_12, 50, 50);
        lv_image_set_src(obj_12, "A:images/l12.png");
    }
    {
        lv_obj_t * obj_13 = lv_image_create(root);
        lv_obj_set_pos(obj_13, 100, 50);
        lv_obj_set_size(obj_13, 50, 50);
        lv_image_set_src(obj_13, "A:images/l13.png");
    }
    {
        lv_obj_t * obj_14 = lv_image_create(root);
        lv_obj_set_pos(obj_14, 150, 50);
        lv_obj_set_size(obj_14, 50, 50);
        lv_image_set_src(obj_14, "A:images/l14.png");
    }
    {
        lv_obj_t * obj_15 = lv_image_create(root);
        lv_obj_set_pos(obj_15, 200, 50);
        lv_obj_set_size(obj_15, 50, 50);
        lv_image_set_src(obj_15, "A:images/l15.png");
    }
    {
        lv_obj_t * obj_16 = lv_image_create(root);
        lv_obj_set_pos(obj_16, 250, 50);
        lv_obj_set_size(obj_16, 50, 50);
        lv_image_set_src(obj_16, "A:images/l16.png");
    }
    {
        lv_obj_t * obj_17 = lv_image_create(root);
        lv_obj_set_pos(obj_17, 300, 50);
        lv_obj_set_size(obj_17, 50, 50);
        lv_image_set_src(obj_17, "A:images/l17.png");
    }
    {
        lv_obj_t * obj_18 = lv_image_create(root);
        lv_obj_set_pos(obj_18, 350, 50);
        lv_obj_set_size(obj_18, 50, 50);
        lv_image_set_src(obj_18, "A:images/l18.png");
    }
    {
        lv_obj_t * obj_19 = lv_image_create(root);
        lv_obj_set_pos(obj_19, 400, 50);
        lv_obj_set_size(obj_19, 50, 50);
        lv_image_set_src(obj_19, "A:images/l19.png");
    }
    {
        lv_obj_t * obj_20 = lv_image_create(root);
        lv_obj_set_pos(obj_20, 450, 50);
        lv_obj_set_size(obj_20, 50, 50);
        lv_image_set_src(obj_20, "A:images/l20.png");
    }
    {
        lv_obj_t * obj_21 = lv_image_create(root);
        lv_obj_set_pos(obj_21, 0, 100);
        lv_obj_set_size(obj_21, 50, 50);
        lv_image_set_src(obj_21, "A:images/l21.png");
    }
    {
        lv_obj_t * obj_22 = lv_image_create(root);
        lv_obj_set_pos(obj_22, 50, 100);
        lv_obj_set_size(obj_22, 50, 50);
        lv_image_set_src(obj_22, "A:images/l22.png");
    }
    {
        lv_obj_t * obj_23 = lv_image_create(root);
        lv_obj_set_pos(obj_23, 100, 100);
        lv_obj_set_size(obj_23, 50, 50);
        lv_image_set_src(obj_23, "A:images/l23.png");
    }
    {
        lv_obj_t * obj_24 = lv_image_create(root);
        lv_obj_set_pos(obj_24, 150, 100);
        lv_obj_set_size(obj_24, 50, 50);
        lv_image_set_src(obj_24, "A:images/l24.png");
    }
    {
        lv_obj_t * obj_25 = lv_image_create(root);
        lv_obj_set_pos(obj_25, 200, 100);
        lv_obj_set_size(obj_25, 50, 50);
        lv_image_set_src(obj_25, "A:images/l25.png");
    }
    {
        lv_obj_t * obj_26 = lv_image_create(root);
        lv_obj_set_pos(obj_26, 250, 100);
        lv_obj_set_size(obj_26, 50, 50);
        lv_image_set_src(obj_26, "A:images/l26.png");
    }
    {
        lv_obj_t * obj_27 = lv_image_create(root);
        lv_obj_set_pos(obj_27, 300, 100);
        lv_obj_set_size(obj_27, 50, 50);
        lv_image_set_src(obj_27, "A:images/l27.png");
    }
    {
        lv_obj_t * obj_28 = lv_image_create(root);
        lv_obj_set_pos(obj_28, 350, 100);
        lv_obj_set_size(obj_28, 50, 50);
        lv_image_set_src(obj_28, "A:images/l28.png");
    }
    {
        lv_obj_t * obj_29 = lv_image_create(root);
        lv_obj_set_pos(obj_29, 400, 100);
        lv_obj_set_size(obj_29, 50, 50);
        lv_image_set_src(obj_29, "A:images/l29.png");
    }
    {
        lv_obj_t * obj_30 = lv_image_create(root);
        lv_obj_set_pos(obj_30, 450, 100);
        lv_obj_set_size(obj_30, 50, 50);
        lv_image_set_src(obj_30, "A:images/l30.png");
    }
    {
        lv_obj_t * obj_31 = lv_image_create(root);
        lv_obj_set_pos(obj_31, 0, 150);
        lv_obj_set_size(obj_31, 50, 50);
        lv_image_set_src(obj_31, "A:images/l31.png");
    }
    {
        lv_obj_t * obj_32 = lv_image_create(root);
        lv_obj_set_pos(obj_32, 50, 150);
        lv_obj_set_size(obj_32, 50, 50);
        lv_image_set_src(obj_32, "A:images/l32.png");
    }
    {
        lv_obj_t * obj_33 = lv_image_create(root);
        lv_obj_set_pos(obj_33, 100, 150);
        lv_obj_set_size(obj_33, 50, 50);
        lv_image_set_src(obj_33, "A:images/l33.png");
    }
    {
        lv_obj_t * obj_34 = lv_image_create(root);
        lv_obj_set_pos(obj_34, 150, 150);
        lv_obj_set_size(obj_34, 50, 50);
        lv_image_set_src(obj_34, "A:images/l34.png");
    }
    {
        lv_obj_t * obj_35 = lv_image_create(root);
        lv_obj_set_pos(obj_35, 200, 150);
        lv_obj_set_size(obj_35, 50, 50);
        lv_image_set_src(obj_35, "A:images/l35.png");
    }
    {
        lv_obj_t * obj_36 = lv_image_create(root);
        lv_obj_set_pos(obj_36, 250, 150);
        lv_obj_set_size(obj_36, 50, 50);
        lv_image_set_src(obj_36, "A:images/l36.png");
    }
    {
        lv_obj_t * obj_37 = lv_image_create(root);
        lv_obj_set_pos(obj_37, 300, 150);
        lv_obj_set_size(obj_37, 50, 50);
        lv_image_set_src(obj_37, "A:images/l37.png");
    }
    {
        lv_obj_t * obj_38 = lv_image_create(root);
        lv_obj_set_pos(obj_38, 350, 150);
        lv_obj_set_size(obj_38, 50, 50);
        lv_image_set_src(obj_38, "A:images/l38.png");
    }
    {
        lv_obj_t * obj_39 = lv_image_create(root);
        lv_obj_set_pos(obj_39, 400, 150);
        lv_obj_set_size(obj_39, 50, 50);
        lv_image_set_src(obj_39, "A:images/l39.png");
    }
    {
        lv_obj_t * obj_40 = lv_image_create(root);
        lv_obj_set_pos(obj_40, 450, 150);
        lv_obj_set_size(obj_40, 50, 50);
        lv_image_set_src(obj_40, "A:images/l40.png");
    }
    {
        lv_obj_t * obj_41 = lv_image_create(root);
        lv_obj_set_pos(obj_41, 0, 200);
        lv_obj_set_size(obj_41, 50, 50);
        lv_image_set_src(obj_41, "A:images/l41.png");
    }
    {
        lv_obj_t * obj_42 = lv_image_create(root);
        lv_obj_set_pos(obj_42, 50, 200);
        lv_obj_set_size(obj_42, 50, 50);
        lv_image_set_src(obj_42, "A:images/l42.png");
    }
    {
        lv_obj_t * obj_43 = lv_image_create(root);
        lv_obj_set_pos(obj_43, 100, 200);
        lv_obj_set_size(obj_43, 50, 50);
        lv_image_set_src(obj_43, "A:images/l43.png");
    }
    {
        lv_obj_t * obj_44 = lv_image_create(root);
        lv_obj_set_pos(obj_44, 150, 200);
        lv_obj_set_size(obj_44, 50, 50);
        lv_image_set_src(obj_44, "A:images/l44.png");
    }
    {
        lv_obj_t * obj_45 = lv_image_create(root);
        lv_obj_set_pos(obj_45, 200, 200);
        lv_obj_set_size(obj_45, 50, 50);
        lv_image_set_src(obj_45, "A:images/l45.png");
    }
    {
        lv_obj_t * obj_46 = lv_image_create(root);
        lv_obj_set_pos(obj_46, 250, 200);
        lv_obj_set_size(obj_46, 50, 50);
        lv_image_set_src(obj_46, "A:images/l46.png");
    }
    {
        lv_obj_t * obj_47 = lv_image_create(root);
        lv_obj_set_pos(obj_47, 300, 200);
        lv_obj_set_size(obj_47, 50, 50);
        lv_image_set_src(obj_47, "A:images/l47.png");
    }
    {
        lv_obj_t * obj_48 = lv_image_create(root);
        lv_obj_set_pos(obj_48, 350, 200);
        lv_obj_set_size(obj_48, 50, 50);
        lv_image_set_src(obj_48, "A:images/l48.png");
    }
    {
        lv_obj_t * obj_49 = lv_image_create(root);
        lv_obj_set_pos(obj_49, 400, 200);
        lv_obj_set_size(obj_49, 50, 50);
        lv_image_set_src(obj_49, "A:images/l49.png");
    }
    {
        lv_obj_t * obj_50 = lv_image_create(root);
        lv_obj_set_pos(obj_50, 450, 200);
        lv_obj_set_size(obj_50, 50, 50);
        lv_image_set_src(obj_50, "A:images/l50.png");
    }
    {
        lv_obj_t * obj_51 = lv_image_create(root);
        lv_obj_set_pos(obj_51, 0, 250);
        lv_obj_set_size(obj_51, 50, 50);
        lv_image_set_src(obj_51, "A:images/l51.png");
    }
    {
        lv_obj_t * obj_52 = lv_image_create(root);
        lv_obj_set_pos(obj_52, 50, 250);
        lv_obj_set_size(obj_52, 50, 50);
        lv_image_set_src(obj_52, "A:images/l52.png");
    }
    {
        lv_obj_t * obj_53 = lv_image_create(root);
        lv_obj_set_pos(obj_53, 100, 250);
        lv_obj_set_size(obj_53, 50, 50);
        lv_image_set_src(obj_53, "A:images/l53.png");
    }
    {
        lv_obj_t * obj_54 = lv_image_create(root);
        lv_obj_set_pos(obj_54, 150, 250);
        lv_obj_set_size(obj_54, 50, 50);
        lv_image_set_src(obj_54, "A:images/l54.png");
    }
    {
        lv_obj_t * obj_55 = lv_image_create(root);
        lv_obj_set_pos(obj_55, 200, 250);
        lv_obj_set_size(obj_55, 50, 50);
        lv_image_set_src(obj_55, "A:images/l55.png");
    }
    {
        lv_obj_t * obj_56 = lv_image_create(root);
        lv_obj_set_pos(obj_56, 250, 250);
        lv_obj_set_size(obj_56, 50, 50);
        lv_image_set_src(obj_56, "A:images/l56.png");
    }
    {
        lv_obj_t * obj_57 = lv_image_create(root);
        lv_obj_set_pos(obj_57, 300, 250);
        lv_obj_set_size(obj_57, 50, 50);
        lv_image_set_src(obj_57, "A:images/l57.png");
    }
    {
        lv_obj_t * obj_58 = lv_image_create(root);
        lv_obj_set_pos(obj_58, 350, 250);
        lv_obj_set_size(obj_58, 50, 50);
        lv_image_set_src(obj_58, "A:images/l58.png");
    }
    {
        lv_obj_t * obj_59 = lv_image_create(root);
        lv_obj_set_pos(obj_59, 400, 250);
        lv_obj_set_size(obj_59, 50, 50);
        lv_image_set_src(obj_59, "A:images/l59.png");
    }
    {
        lv_obj_t * obj_60 = lv_image_create(root);
        lv_obj_set_pos(obj_60, 450, 250);
        lv_obj_set_size(obj_60, 50, 50);
        lv_image_set_src(obj_60, "A:images/l60.png");
    }
    {
        lv_obj_t * obj_61 = lv_image_create(root);
        lv_obj_set_pos(obj_61, 0, 300);
        lv_obj_set_size(obj_61, 50, 50);
        lv_image_set_src(obj_61, "A:images/l61.png");
    }
    {
        lv_obj_t * obj_62 = lv_image_create(root);
        lv_obj_set_pos(obj_62, 50, 300);
        lv_obj_set_size(obj_62, 50, 50);
        lv_image_set_src(obj_62, "A:images/l62.png");
    }
    {
        lv_obj_t * obj_63 = lv_image_create(root);
        lv_obj_set_pos(obj_63, 100, 300);
        lv_obj_set_size(obj_63, 50, 50);
        lv_image_set_src(obj_63, "A:images/l63.png");
    }
    {
        lv_obj_t * obj_64 = lv_image_create(root);
        lv_obj_set_pos(obj_64, 150, 300);
        lv_obj_set_size(obj_64, 50, 50);
        lv_image_set_src(obj_64, "A:images/l64.png");
    }
    {
        lv_obj_t * obj_65 = lv_image_create(root);
        lv_obj_set_pos(obj_65, 200, 300);
        lv_obj_set_size(obj_65, 50, 50);
        lv_image_set_src(obj_65, "A:images/l65.png");
    }
    {
        lv_obj_t * obj_66 = lv_image_create(root);
        lv_obj_set_pos(obj_66, 250, 300);
        lv_obj_set_size(obj_66, 50, 50);
        lv_image_set_src(obj_66, "A:images/l66.png");
    }
    {
        lv_obj_t * obj_67 = lv_image_create(root);
        lv_obj_set_pos(obj_67, 300, 300);
        lv_obj_set_size(obj_67, 50, 50);
        lv_image_set_src(obj_67, "A:images/l67.png");
    }
    {
        lv_obj_t * obj_68 = lv_image_create(root);
        lv_obj_set_pos(obj_68, 350, 300);
        lv_obj_set_size(obj_68, 50, 50);
        lv_image_set_src(obj_68, "A:images/l68.png");
    }
    {
        lv_obj_t * obj_69 = lv_image_create(root);
        lv_obj_set_pos(obj_69, 400, 300);
        lv_obj_set_size(obj_69, 50, 50);
        lv_image_set_src(obj_69, "A:images/l69.png");
    }
    {
        lv_obj_t * obj_70 = lv_image_create(root);
        lv_obj_set_pos(obj_70, 450, 300);
        lv_obj_set_size(obj_70, 50, 50);
        lv_image_set_src(obj_70, "A:images/l70.png");
    }
    {
        lv_obj_t * obj_71 = lv_image_create(root);
        lv_obj_set_pos(obj_71, 0, 350);
        lv_obj_set_size(obj_71, 50, 50);
        lv_image_set_src(obj_71, "A:images/l71.png");
    }
    {
        lv_obj_t * obj_72 = lv_image_create(root);
        lv_obj_set_pos(obj_72, 50, 350);
        lv_obj_set_size(obj_72, 50, 50);
        lv_image_set_src(obj_72, "A:images/l72.png");
    }
    {
        lv_obj_t * obj_73 = lv_image_create(root);
        lv_obj_set_pos(obj_73, 100, 350);
        lv_obj_set_size(obj_73, 50, 50);
        lv_image_set_src(obj_73, "A:images/l73.png");
    }
    {
        lv_obj_t * obj_74 = lv_image_create(root);
        lv_obj_set_pos(obj_74, 150, 350);
        lv_obj_set_size(obj_74, 50, 50);
        lv_image_set_src(obj_74, "A:images/l74.png");
    }
    {
        lv_obj_t * obj_75 = lv_image_create(root);
        lv_obj_set_pos(obj_75, 200, 350);
        lv_obj_set_size(obj_75, 50, 50);
        lv_image_set_src(obj_75, "A:images/l75.png");
    }
    {
        lv_obj_t * obj_76 = lv_image_create(root);
        lv_obj_set_pos(obj_76, 250, 350);
        lv_obj_set_size(obj_76, 50, 50);
        lv_image_set_src(obj_76, "A:images/l76.png");
    }
    {
        lv_obj_t * obj_77 = lv_image_create(root);
        lv_obj_set_pos(obj_77, 300, 350);
        lv_obj_set_size(obj_77, 50, 50);
        lv_image_set_src(obj_77, "A:images/l77.png");
    }
    {
        lv_obj_t * obj_78 = lv_image_create(root);
        lv_obj_set_pos(obj_78, 350, 350);
        lv_obj_set_size(obj_78, 50, 50);
        lv_image_set_src(obj_78, "A:images/l78.png");
    }
    {
        lv_obj_t * obj_79 = lv_image_create(root);
        lv_obj_set_pos(obj_79, 400, 350);
        lv_obj_set_size(obj_79, 50, 50);
        lv_image_set_src(obj_79, "A:images/l79.png");
    }
    {
        lv_obj_t * obj_80 = lv_image_create(root);
        lv_obj_set_pos(obj_80, 450, 350);
        lv_obj_set_size(obj_80, 50, 50);
        lv_image_set_src(obj_80, "A:images/l80.png");
    }
    {
        lv_obj_t * obj_81 = lv_image_create(root);
        lv_obj_set_pos(obj_81, 0, 400);
        lv_obj_set_size(obj_81, 50, 50);
        lv_image_set_src(obj_81, "A:images/l81.png");
    }
    {
        lv_obj_t * obj_82 = lv_image_create(root);
        lv_obj_set_pos(obj_82, 50, 400);
        lv_obj_set_size(obj_82, 50, 50);
        lv_image_set_src(obj_82, "A:images/l82.png");
    }
    {
        lv_obj_t * obj_83 = lv_image_create(root);
        lv_obj_set_pos(obj_83, 100, 400);
        lv_obj_set_size(obj_83, 50, 50);
        lv_image_set_src(obj_83, "A:images/l83.png");
    }
    {
        lv_obj_t * obj_84 = lv_image_create(root);
        lv_obj_set_pos(obj_84, 150, 400);
        lv_obj_set_size(obj_84, 50, 50);
        lv_image_set_src(obj_84, "A:images/l84.png");
    }
    {
        lv_obj_t * obj_85 = lv_image_create(root);
        lv_obj_set_pos(obj_85, 200, 400);
        lv_obj_set_size(obj_85, 50, 50);
        lv_image_set_src(obj_85, "A:images/l85.png");
    }
    {
        lv_obj_t * obj_86 = lv_image_create(root);
        lv_obj_set_pos(obj_86, 250, 400);
        lv_obj_set_size(obj_86, 50, 50);
        lv_image_set_src(obj_86, "A:images/l86.png");
    }
    {
        lv_obj_t * obj_87 = lv_image_create(root);
        lv_obj_set_pos(obj_87, 300, 400);
        lv_obj_set_size(obj_87, 50, 50);
        lv_image_set_src(obj_87, "A:images/l87.png");
    }
    {
        lv_obj_t * obj_88 = lv_image_create(root);
        lv_obj_set_pos(obj_88, 350, 400);
        lv_obj_set_size(obj_88, 50, 50);
        lv_image_set_src(obj_88, "A:images/l88.png");
    }
    {
        lv_obj_t * obj_89 = lv_image_create(root);
        lv_obj_set_pos(obj_89, 400, 400);
        lv_obj_set_size(obj_89, 50, 50);
        lv_image_set_src(obj_89, "A:images/l89.png");
    }
    {
        lv_obj_t * obj_90 = lv_image_create(root);
        lv_obj_set_pos(obj_90, 450, 400);
        lv_obj_set_size(obj_90, 50, 50);
        lv_image_set_src(obj_90, "A:images/l90.png");
    }
    {
        lv_obj_t * obj_91 = lv_image_create(root);
        lv_obj_set_pos(obj_91, 0, 450);
        lv_obj_set_size(obj_91, 50, 50);
        lv_image_set_src(obj_91, "A:images/l91.png");
    }
    {
        lv_obj_t * obj_92 = lv_image_create(root);
        lv_obj_set_pos(obj_92, 50, 450);
        lv_obj_set_size(obj_92, 50, 50);
        lv_image_set_src(obj_92, "A:images/l92.png");
    }
    {
        lv_obj_t * obj_93 = lv_image_create(root);
        lv_obj_set_pos(obj_93, 100, 450);
        lv_obj_set_size(obj_93, 50, 50);
        lv_image_set_src(obj_93, "A:images/l93.png");
    }
    {
        lv_obj_t * obj_94 = lv_image_create(root);
        lv_obj_set_pos(obj_94, 150, 450);
        lv_obj_set_size(obj_94, 50, 50);
        lv_image_set_src(obj_94, "A:images/l94.png");
    }
    {
        lv_obj_t * obj_95 = lv_image_create(root);
        lv_obj_set_pos(obj_95, 200, 450);
        lv_obj_set_size(obj_95, 50, 50);
        lv_image_set_src(obj_95, "A:images/l95.png");
    }
    {
        lv_obj_t * obj_96 = lv_image_create(root);
        lv_obj_set_pos(obj_96, 250, 450);
        lv_obj_set_size(obj_96, 50, 50);
        lv_image_set_src(obj_96, "A:images/l96.png");
    }
    {
        lv_obj_t * obj_97 = lv_image_create(root);
        lv_obj_set_pos(obj_97, 300, 450);
        lv_obj_set_size(obj_97, 50, 50);
        lv_image_set_src(obj_97, "A:images/l97.png");
    }
    {
        lv_obj_t * obj_98 = lv_image_create(root);
        lv_obj_set_pos(obj_98, 350, 450);
        lv_obj_set_size(obj_98, 50, 50);
        lv_image_set_src(obj_98, "A:images/l98.png");
    }
    {
        lv_obj_t * obj_99 = lv_image_create(root);
        lv_obj_set_pos(obj_99, 400, 450);
        lv_obj_set_size(obj_99, 50, 50);
        lv_image_set_src(obj_99, "A:images/l99.png");
    }
    {
        lv_obj_t * obj_100 = lv_image_create(root);
        lv_obj_set_pos(obj_100, 450, 450);
        lv_obj_set_size(obj_100, 50, 50);
        lv_image_set_src(obj_100, "A:images/l100.png");
    }
    return root;
}
