export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 140px;
        image-fit: contain;
        source: @image-url("images/styled_1.png");
        width: 80px;
        x: 10px;
        y: 30px;
    }
    Image {
        height: 140px;
        image-fit: contain;
        source: @image-url("images/styled_2.png");
        width: 80px;
        x: 100px;
        y: 30px;
    }
    Image {
        height: 140px;
        image-fit: contain;
        source: @image-url("images/styled_3.png");
        width: 80px;
        x: 190px;
        y: 30px;
    }
}
