export component MainWindow inherits Window {
    height: 300px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 300px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Roboto";
        font-size: 21px;
        height: 28px;
        horizontal-alignment: left;
        text: "Rotated";
        width: 99px;
        x: 71px;
        y: 88px;
    }
}
