export component MainWindow inherits Window {
    height: 300px;
    title: "";
    width: 400px;
    x: 0px;
    y: 0px;
    Image {
        height: 300px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 400px;
        x: 0px;
        y: 0px;
    }
    Text {
        clip: true;
        color: #000000;
        font-family: "Roboto";
        font-size: 48px;
        height: 63px;
        horizontal-alignment: left;
        text: "Flag";
        vertical-alignment: bottom;
        width: 91px;
        x: 100px;
        y: 100px;
    }
}
