export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Rectangle {
        height: 200px;
        width: 300px;
        x: 0px;
        y: 0px;
        Rectangle {
            background: @linear-gradient(-270.000deg, #ff0000 0%, #ff0000 100%);
            height: 200px;
            width: 300px;
            x: 0px;
            y: 0px;
        }
    }
}
