export component MainWindow inherits Window {
    height: 240px;
    title: "";
    width: 320px;
    x: 0px;
    y: 0px;
    Rectangle {
        background: #5d5206;
        height: 240px;
        width: 320px;
        x: 0px;
        y: 0px;
    }
    Rectangle {
        height: 62px;
        width: 163px;
        x: 48px;
        y: 79px;
        Rectangle {
            background: #f5f5ed;
            height: 60px;
            width: 160px;
            x: 2px;
            y: 1px;
        }
    }
    Rectangle {
        height: 34px;
        width: 157px;
        x: 52px;
        y: 80px;
        Rectangle {
            background: #f7e790;
            height: 32px;
            width: 155px;
            x: 1px;
            y: 1px;
        }
    }
    Text {
        clip: true;
        color: #000000;
        font-family: "Source Han Sans";
        font-size: 30px;
        height: 44px;
        horizontal-alignment: center;
        text: "Example1";
        vertical-alignment: center;
        width: 160px;
        x: 50px;
        y: 71px;
    }
}
