export component MainWindow inherits Window {
    height: 240px;
    title: "";
    width: 320px;
    x: 0px;
    y: 0px;
    Rectangle {
        background: #f7e790;
        height: 240px;
        width: 320px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Source Han Sans";
        font-size: 30px;
        height: 49px;
        horizontal-alignment: center;
        text: ".";
        vertical-alignment: center;
        width: 9px;
        x: 125px;
        y: 71px;
    }
}
