export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        image-fit: contain;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        height: 150px;
        image-fit: contain;
        source: @image-url("images/partial.png");
        width: 150px;
        x: 25px;
        y: 25px;
    }
}
