export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.721569;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.8;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.490196;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.101961;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.588235;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.129412;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.419608;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.741176;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.278431;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.2;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.411765;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.85098;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.231373;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.529412;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.631373;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.768627;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.368627;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.529412;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.14902;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.8;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.368627;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.4;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.878431;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.670588;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.380392;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.811765;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.478431;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.101961;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.34902;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.819608;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.568627;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.658824;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.74902;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.729412;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.321569;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.231373;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.411765;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.670588;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.290196;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.109804;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.45098;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.831373;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.831373;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.309804;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.690196;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.411765;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.721569;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.388235;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.611765;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
    Image {
        image-fit: contain;
        opacity: 0.458824;
        source: @image-url("images/");
        x: 0px;
        y: 0px;
    }
}
