export component MainWindow inherits Window {
    height: 1080px;
    title: "";
    width: 1920px;
    x: 0px;
    y: 0px;
    Image {
        height: 1080px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 1920px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Roboto";
        font-size: 48px;
        height: 63px;
        horizontal-alignment: left;
        text: "Landscape";
        width: 234px;
        x: 800px;
        y: 490px;
    }
}
