export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 40px;
        image-fit: contain;
        source: @image-url("images/layer_1.png");
        width: 40px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 40px;
        image-fit: contain;
        source: @image-url("images/layer_2.png");
        width: 40px;
        x: 30px;
        y: 30px;
    }
    Image {
        height: 40px;
        image-fit: contain;
        source: @image-url("images/layer_3.png");
        width: 40px;
        x: 60px;
        y: 60px;
    }
    Image {
        height: 40px;
        image-fit: contain;
        source: @image-url("images/layer_4.png");
        width: 40px;
        x: 90px;
        y: 90px;
    }
    Image {
        height: 40px;
        image-fit: contain;
        source: @image-url("images/layer_5.png");
        width: 40px;
        x: 120px;
        y: 120px;
    }
}
