/* Generated by Qt PSD Exporter - LVGL C exporter */
#include "main_screen.h"

const int32_t main_screen_width = 640;
const int32_t main_screen_height = 240;

lv_obj_t * main_screen_create(lv_obj_t * parent)
{
    lv_obj_t * root = lv_obj_create(parent);
    lv_obj_set_pos(root, 0, 0);
    lv_obj_set_size(root, 640, 240);
    lv_obj_set_style_pad_all(root, 0, 0);
    lv_obj_set_style_border_width(root, 0, 0);
    lv_obj_set_style_radius(root, 0, 0);
    lv_obj_set_style_bg_opa(root, 0, 0);
    lv_obj_set_scrollbar_mode(root, LV_SCROLLBAR_MODE_OFF);
    {
        lv_obj_t * obj_0 = lv_obj_create(root);
        lv_obj_set_pos(obj_0, 0, 0);
        lv_obj_set_size(obj_0, 640, 240);
        lv_obj_set_style_bg_color(obj_0, lv_color_hex(0x012401), 0);
        lv_obj_set_style_bg_opa(obj_0, 255, 0);
    }
    {
        lv_obj_t * obj_1 = lv_label_create(root);
        lv_obj_set_pos(obj_1, 30, 16);
        lv_obj_set_size(obj_1, 120, 72);
        lv_obj_set_style_text_align(obj_1, LV_TEXT_ALIGN_CENTER, 0);
        lv_obj_set_style_text_color(obj_1, lv_color_hex(0xffffff), 0);
        lv_obj_set_style_text_font(obj_1, &lv_font_montserrat_48, 0);
        lv_label_set_text(obj_1, "12pt");
    }
    {
        lv_obj_t * obj_2 = lv_label_create(root);
        lv_obj_set_pos(obj_2, 150, 18);
        lv_obj_set_size(obj_2, 478, 217);
        lv_obj_set_style_text_align(obj_2, LV_TEXT_ALIGN_CENTER, 0);
        lv_obj_set_style_text_color(obj_2, lv_color_hex(0xffffff), 0);
        lv_obj_set_style_text_font(obj_2, &lv_font_montserrat_48, 0);
        lv_label_set_text(obj_2, "150px");
    }
    return root;
}
