/* Generated by Qt PSD Exporter - LVGL C exporter */
#include "main_screen.h"

const int32_t main_screen_width = 300;
const int32_t main_screen_height = 200;

lv_obj_t * main_screen_create(lv_obj_t * parent)
{
    static lv_grad_dsc_t grad_opacity_gradient_0;
    {
        static const lv_color_t stops_opacity_gradient_0_colors[] = { LV_COLOR_MAKE(0xff, 0x0, 0x0), LV_COLOR_MAKE(0xff, 0x0, 0x0), };
        static const lv_opa_t stops_opacity_gradient_0_opa[] = { 255, 0, };
        static const uint8_t stops_opacity_gradient_0_fracs[] = { 0, 255, };
        lv_grad_linear_init(&grad_opacity_gradient_0, 0, 100, 300, 100, LV_GRAD_EXTEND_PAD);
        lv_grad_init_stops(&grad_opacity_gradient_0, stops_opacity_gradient_0_colors, stops_opacity_gradient_0_opa, stops_opacity_gradient_0_fracs, 2);
    }

    lv_obj_t * root = lv_obj_create(parent);
    lv_obj_set_pos(root, 0, 0);
    lv_obj_set_size(root, 300, 200);
    lv_obj_set_style_pad_all(root, 0, 0);
    lv_obj_set_style_border_width(root, 0, 0);
    lv_obj_set_style_radius(root, 0, 0);
    lv_obj_set_style_bg_opa(root, 0, 0);
    lv_obj_set_scrollbar_mode(root, LV_SCROLLBAR_MODE_OFF);
    {
        lv_obj_t * obj_0 = lv_obj_create(root);
        lv_obj_set_pos(obj_0, 0, 0);
        lv_obj_set_size(obj_0, 300, 200);
        lv_obj_set_style_bg_grad(obj_0, &grad_opacity_gradient_0, 0);
        lv_obj_set_style_bg_opa(obj_0, 255, 0);
        lv_obj_set_style_border_width(obj_0, 0, 0);
    }
    return root;
}
