export component MainWindow inherits Window {
    height: 300px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Rectangle {
        height: 300px;
        width: 300px;
        x: 0px;
        y: 0px;
        Rectangle {
            background: #c8c8c8;
            height: 300px;
            width: 300px;
            x: 0px;
            y: 0px;
        }
    }
    Text {
        color: #000080;
        font-family: "Roboto";
        font-size: 24px;
        height: 32px;
        horizontal-alignment: left;
        text: "Foreground Text";
        vertical-alignment: bottom;
        width: 174px;
        x: 50px;
        y: 125px;
    }
}
