export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 80px;
        image-fit: contain;
        source: @image-url("images/flipped_v.png");
        width: 160px;
        x: 20px;
        y: 20px;
    }
}
