name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
#        os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
        qt: ['6.8.0']
        include:
          - os: ubuntu-latest
            host: linux
            arch: linux_gcc_64
#          - os: windows-latest
#            host: windows
#            arch: win64_msvc2022_64
#          - os: macos-latest
#            host: mac
#            arch: clang_64

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Qt
        uses: Jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt }}
          arch: ${{ matrix.arch }}
          archives: 'qtbase icu'
          tools: 'tools_cmake tools_ninja'
          cache: true
          setup-python: 'true'

#      - name: Configure CMake (Windows)
#        if: runner.os == 'Windows'
#        shell: pwsh
#        run: |
#          qt-cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Configure CMake (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          qt-cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --parallel

      - name: Install
        run: |
          cmake --install build

      - name: Test
        working-directory: build
        run: |
          ctest --output-on-failure
