name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#        os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest, macos-latest]
        qt: ['6.8.0']
        include:
          - os: ubuntu-latest
            host: linux
            arch: linux_gcc_64
            generator: 'Ninja'
            archives: 'qtbase icu'
#          - os: windows-latest
#            host: windows
#            arch: win64_msvc2022_64
#            generator: 'Visual Studio 17 2022'
#            generator: 'Ninja'
#            archives: 'qtbase'
          - os: macos-latest
            host: mac
            arch: clang_64
            generator: 'Ninja'
            archives: 'qtbase'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install system dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxcb-cursor0 \
            libxcb-cursor-dev \
            libxcb-xinerama0 \
            libxcb-xinput0 \
            libxcb-render0 \
            libxcb-shape0 \
            libxcb-randr0 \
            libgl1-mesa-glx \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-util1

      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install ninja

      - name: Install Qt
        uses: Jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt }}
          arch: ${{ matrix.arch }}
          archives: ${{ matrix.archives }}
          tools: 'tools_cmake tools_ninja'
          cache: true
          setup-python: 'true'
          install-deps: 'true'

      - name: Configure
        run: |
          qt-cmake -B build -G "${{ matrix.generator }}" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Wno-error=switch -Wno-error=unused-parameter -Wno-error=missing-field-initializers"

      - name: Build
        run: |
          cmake --build build --parallel

      - name: Install
        run: |
          cmake --install build

      - name: Test
        working-directory: build
        run: |
          ctest --output-on-failure
