name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#        os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]
        qt: ['6.8.0']
        include:
#          - os: ubuntu-latest
#            host: linux
#            arch: linux_gcc_64
#            generator: 'Ninja'
#            archives: 'qtbase icu'
#            no-error:  ''
          - os: windows-latest
            host: windows
            arch: win64_msvc2022_64
            generator: 'Visual Studio 17 2022'
            archives: 'qtbase'
            no-error: ''
#          - os: macos-latest
#            host: mac
#            arch: clang_64
#            generator: 'Ninja'
#            archives: 'qtbase'
#            no-error:  '-DCMAKE_CXX_FLAGS="-Wno-error=switch -Wno-error=unused-parameter -Wno-error=missing-field-initializers"'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Qt
        uses: Jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt }}
          arch: ${{ matrix.arch }}
          archives: ${{ matrix.archives }}
          tools: 'tools_cmake tools_ninja'
          cache: true
          setup-python: 'true'
          install-deps: 'true'

      - name: Configure
        run: |
          qt-cmake -B build -G "Visual Studio 17 2022" -A x64 ${{ matrix.no-error }}

      - name: Build
        run: |
          cmake --build build --config Release --parallel

      - name: Install
        run: |
          cmake --install build

      - name: Test
        working-directory: build
        run: |
          ctest --output-on-failure
