export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Roboto";
        font-size: 100px;
        height: 132px;
        horizontal-alignment: left;
        text: "300 DPI";
        width: 349px;
        x: 30px;
        y: -5px;
    }
}
