export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 400px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 400px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "Sans Serif";
        font-size: 9px;
        height: 23px;
        horizontal-alignment: left;
        text: "";
        width: 79px;
        x: 22px;
        y: 82px;
    }
    Text {
        color: #000000;
        font-family: "Sans Serif";
        font-size: 9px;
        height: 19px;
        horizontal-alignment: left;
        text: "";
        width: 47px;
        x: 146px;
        y: 82px;
    }
}
