export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/d002afde4b1f5710.png");
        width: 60px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 200px;
        image-fit: contain;
        opacity: 0.74902;
        source: @image-url("images/8ecc52d841cb1fcf.png");
        width: 60px;
        x: 60px;
        y: 0px;
    }
    Image {
        height: 200px;
        image-fit: contain;
        opacity: 0.501961;
        source: @image-url("images/4bbbc83c0c2897a9.png");
        width: 60px;
        x: 120px;
        y: 0px;
    }
    Image {
        height: 200px;
        image-fit: contain;
        opacity: 0.25098;
        source: @image-url("images/08dd8a50bb4e0e66.png");
        width: 60px;
        x: 180px;
        y: 0px;
    }
    Image {
        height: 200px;
        image-fit: contain;
        opacity: 0.101961;
        source: @image-url("images/d3d4e660567819cb.png");
        width: 60px;
        x: 240px;
        y: 0px;
    }
}
