export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 300px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 300px;
        x: 0px;
        y: 0px;
    }
    Path {
        fill: #ff8000;
        height: 102px;
        stroke: transparent;
        width: 262px;
        x: 19px;
        y: 49px;
        MoveTo {
            x: 131.00;
            y: 1.00;
        }
        CubicTo {
            control-1-x: 202.80;
            control-1-y: 1.00;
            control-2-x: 261.00;
            control-2-y: 23.39;
            x: 261.00;
            y: 51.00;
        }
        CubicTo {
            control-1-x: 261.00;
            control-1-y: 78.61;
            control-2-x: 202.80;
            control-2-y: 101.00;
            x: 131.00;
            y: 101.00;
        }
        CubicTo {
            control-1-x: 59.20;
            control-1-y: 101.00;
            control-2-x: 1.00;
            control-2-y: 78.61;
            x: 1.00;
            y: 51.00;
        }
        CubicTo {
            control-1-x: 1.00;
            control-1-y: 23.39;
            control-2-x: 59.20;
            control-2-y: 1.00;
            x: 131.00;
            y: 1.00;
        }
    }
}
