export component MainWindow inherits Window {
    height: 200px;
    title: "";
    width: 200px;
    x: 0px;
    y: 0px;
    Image {
        height: 200px;
        image-fit: contain;
        source: @image-url("images/background.png");
        width: 200px;
        x: 0px;
        y: 0px;
    }
    Text {
        clip: true;
        color: #000000;
        font-family: "Roboto";
        font-size: 24px;
        height: 32px;
        horizontal-alignment: left;
        text: "Hello";
        vertical-alignment: bottom;
        width: 55px;
        x: 50px;
        y: 75px;
    }
}
